### ISSUE TITLE
Cannot assign value of type 'TLPhotosPickerConfigure' to type 'TLPhotosPickerConfigure'

### ISSUE THREAD

**Issue by mding5692** [tilltue/TLPhotoPicker#10]
I have these compiler errors:
![screen shot 2017-05-23 at 1 14 48 pm](https://cloud.githubusercontent.com/assets/9067177/26366644/da0d1c60-3fb9-11e7-887e-a5ebde2b700a.png)

This is my configure:
![screen shot 2017-05-23 at 1 15 36 pm](https://cloud.githubusercontent.com/assets/9067177/26366666/f04589b8-3fb9-11e7-91b9-d025c849cbf9.png)

And my setup viewcontroller:
![screen shot 2017-05-23 at 1 16 17 pm](https://cloud.githubusercontent.com/assets/9067177/26366697/090dc208-3fba-11e7-8a42-5617e1f2171e.png)

Thanks for your work by the way, it looks very good

**Comment by tilltue** [comment]
hi @mding5692 
```swift
fileprivate func configurePhotoLibraryVC() {
        photoLibraryVC.delegate = self
        // set configure value if you want that. configure`s optional.
        let configure = TLPhotosPickerConfigure()
        //ex configure.numberOfColumn = 3
        photoLibraryVC.configure = configure
    }
```
if you used hold 'image picker viewcontroller' reference. show this.
https://github.com/tilltue/TLPhotoPicker/issues/2

**Comment by mding5692** [comment]
Hi @tilltue, thanks for responding, that works but I dont want livePhotos or videos so i turned those off:
![screen shot 2017-05-24 at 11 32 07 pm](https://cloud.githubusercontent.com/assets/9067177/26434867/443b7dd2-40d9-11e7-8ee1-83774a75c7a1.png)

which causes the error and I would like to be able to customize the configuration.

Thanks again.

**Comment by tilltue** [comment]
@mding5692 
```swift
fileprivate func configurePhotoLibraryVC() {
        photoLibraryVC.delegate = self
        // set configure value if you want that. configure`s optional.
        let configure = TLPhotosPickerConfigure()
        configure.allowedLivePhotos = false
        configure.allowedVideo = false
        //ex configure.numberOfColumn = 3
        photoLibraryVC.configure = configure
    }
```
