### ISSUE TITLE
Warning : 'flatMap' is deprecated

### ISSUE THREAD

**Issue by rizwan95** [tilltue/TLPhotoPicker#101]
Hi team, 

 I just upgraded to Xcode 9.3 and I am starting to get this warning 

'flatMap' is deprecated: Please use compactMap(_:) for the case where closure returns an optional value

Any solution to this?

**Comment by tilltue** [comment]
replace flatMap ->compactMap  https://github.com/tilltue/TLPhotoPicker/pull/102
:)

**Comment by rizwan95** [comment]
Okay I will replace it and push the code :)

**Comment by rizwan95** [comment]
Oh you have already done it :) Great :D
