### ISSUE TITLE
gif 파일 관련 질문입니다

### ISSUE THREAD

**Issue by yunchiri** [tilltue/TLPhotoPicker#103]
gif 파일을 선택후

dismissPhotoPicker() 에서

            asset.photoSize(completion: { (size) in
                print("\(size)")
            })

사이즈를 확인해보니 정상크기로 나오는데요

self.image = asset.fullResolutionImage

여기서

 asset.fullResolutionImage <-- 은 gif의 첫이미지만 있는건가요?

이것을 alamofire를 통해 post 하기 위해 

data로 바꿔줘야하는데

이때는 임시파일에 저장된 데이터를 이용하면 되나요?

아직 코드분석이 제대로 안된 상태에서 급하게 질문을 드려서 죄송합니다 마음이 급해서 ^^;;

**Comment by tilltue** [comment]
@yunchiri 
https://github.com/tilltue/TLPhotoPicker/blob/b183f3bad3a2910003d638a35d539f2d69568457/TLPhotoPicker/Classes/TLAssetsCollection.swift
의 tempCopyMediaFile 함수의 일부분을 떼서 함수를 만드시면 될것 같습니다.

tempCopyMediaFile 함수에서는 imagerequest 의 결과로 받아온 data 를 png로 바꾸는데 바꾸지 않고 사용하시면 될것 같습니다.

**Comment by yunchiri** [comment]
바른 피드백 감사합니다!! 잘쓰고 있습니다 하트뽕뿅~!!
