### ISSUE TITLE
Memory Issue in iPad with live photos

### ISSUE THREAD

**Issue by terenzeyuen** [tilltue/TLPhotoPicker#105]
In iPad, when you select more than 4 or 5 photos with live photos and then tap camera to take photo it will crash with the following error message:
Message from debugger: Terminated due to memory issue

If autoplay set to false, it is ok.

**Comment by tilltue** [comment]
@terenzeyuen 
Can you show me record video when crash app?
My ipad(10.5) is not crashed.

**Comment by MansuriJaved** [comment]
3 or 5 photos selected ipad app crash in Message from debugger: Terminated due to memory issue

**Comment by tilltue** [comment]
@terenzeyuen @MansuriJaved 
I think there is possibility memory issue when imageRequest. 

https://developer.apple.com/documentation/photos/phimagerequestoptionsresizemode
'PHImageRequestOptionsResizeMode' = 'none'
Photos does not resize the image asset.

Monitor Memory Usage
used  **options.resizeMode = .none**
![memory](https://user-images.githubusercontent.com/2108446/39310714-1528cfd2-49a6-11e8-8301-9bc25e23c833.gif)
memory usage : peek 380~500MB

used **options.resizeMode = .exact**
![memory2](https://user-images.githubusercontent.com/2108446/39310715-15590c60-49a6-11e8-9826-69b4cf73b356.gif)
memory usage : peek 60~90MB

**Comment by terenzeyuen** [comment]
I'll try in a while, @MansuriJaved can you test too?
