### ISSUE TITLE
When user tap "use photo" quickly, the photo in album doesn't show up correctly(it's just showed as the default image)

### ISSUE THREAD

**Issue by sonjh1217** [tilltue/TLPhotoPicker#107]
When a user tap "use photo" quickly(after entering camera function tapping camera cell in album), the photo in album doesn't show up correctly(it just showed as the default image)
But after tapping "done" with the photo selected, I can get the info of the image correctly. (11.2.6/ iPhone5s)

**Comment by tilltue** [comment]
I think it should work now. I've pushed a fix for this.
41caa1dcb82db5049966c1c39813f033a630d4b6

**Comment by sonjh1217** [comment]
Thank you. But for now, because 1.5.9 version is on Swift4.1 and it includes compactMap, I cannot build with setting Swift 4.0. It would be nice if you update readme file's requirements section.

**Comment by tilltue** [comment]
@sonjh1217 
Swift 4.0 version compatibility.
fixed: c89e63c1913f90199717740309e89771132b31de
