### ISSUE TITLE
tempCopyMediaFile cannot get progress

### ISSUE THREAD

**Issue by kfung0426** [tilltue/TLPhotoPicker#109]
It is no callback in progressBlock when I copy a video from gallery, any idea?

let asset:TLPHAsset = self.selectedAssets[index]
        if asset.type == .video {
            asset.videoSize { (size) in
                if size > 0{
                    asset.tempCopyMediaFile(convertLivePhotosToPNG: false, progressBlock: { (progress) in
                        print("progress:\(progress)")
                    }, completionBlock: { (url, mimeType) in

                    })
                }
            }
        }

print("progress:\(progress)") is never called and the file is success to get after a long time.

I need to import videos from gallery to in-app document folder.
Previously, I use ALAssetsLibrary and copy the file bytes by bytes, the progress is very fast.
However, PHImageManager is quite slow. Is there any method just copy the file without re-process?

**Comment by tilltue** [comment]
@kfung0426 
check this : 902b5ce9f388b9f615374ad3692c062455523b98
There is many way that export a video. This method was one of them.

It's not yet publish release.
