### ISSUE TITLE
how can i custom cancel button and done button?

### ISSUE THREAD

**Issue by yushuyi** [tilltue/TLPhotoPicker#11]

**Comment by marciliojrs** [comment]
I've created this PR to resolve this issue. It adds two new properties on TLPhotosPickerConfigure: cancelTitle and doneTitle

https://github.com/tilltue/TLPhotoPicker/pull/12

**Comment by yushuyi** [comment]
@marciliojrs i want to change cancel Button icon and done button icon. and title Label color

**Comment by tilltue** [comment]
this commit (db8bcd7ffe768f0ada7399ff756fb44f1870f7c0)
now, you can customizable all properties
