### ISSUE TITLE
Change the AVAssetExportPreset Quality

### ISSUE THREAD

**Issue by kfung0426** [tilltue/TLPhotoPicker#112]
Hi
Please let us change the AVAssetExportPresetHighestQuality to AVAssetExportPresetPassthrough in tempCopyMediaFile() by declaring in TLPhotosPickerConfigure?
My app only need to get the original video without convert.

**Comment by tilltue** [comment]
@kfung0426 
Use copy & paste this code.
```swift3 
public func exportVideoFile(progressBlock:((Float) -> Void)? = nil, completionBlock:@escaping ((URL,String) -> Void)) {
        guard let phAsset = self.phAsset, phAsset.mediaType == .video else { return }
        var type = PHAssetResourceType.video
        guard let resource = (PHAssetResource.assetResources(for: phAsset).filter{ $0.type == type }).first else { return }
        let fileName = resource.originalFilename
        var writeURL: URL? = nil
        if #available(iOS 10.0, *) {
            writeURL = FileManager.default.temporaryDirectory.appendingPathComponent("\(fileName)")
        } else {
            writeURL = URL(fileURLWithPath: NSTemporaryDirectory(), isDirectory: true).appendingPathComponent("\(fileName)")
        }
        guard let localURL = writeURL,let mimetype = MIMEType(writeURL) else { return }
        let options = PHVideoRequestOptions()
        options.isNetworkAccessAllowed = true
        **options.deliveryMode = .highQualityFormat**
        //iCloud download progress
        //options.progressHandler = { (progress, error, stop, info) in
            
        //}
        PHImageManager.default().requestAVAsset(forVideo: phAsset, options: options) { (avasset, avaudioMix, infoDict) in
            guard let avasset = avasset else { return }
            let exportSession = AVAssetExportSession.init(asset: avasset, presetName: AVAssetExportPresetHighestQuality)
            exportSession?.outputURL = localURL
            exportSession?.outputFileType = AVFileType.mov
            exportSession?.exportAsynchronously(completionHandler: {
                completionBlock(localURL,mimetype)
            })
            func checkExportSession() {
                DispatchQueue.global().async { [weak exportSession] in
                    guard let exportSession = exportSession else { return }
                    switch exportSession.status {
                    case .waiting,.exporting:
                        DispatchQueue.main.async {
                            progressBlock?(exportSession.progress)
                        }
                        Thread.sleep(forTimeInterval: 1)
                        checkExportSession()
                    default:
                        break
                    }
                }
            }
            checkExportSession()
        }
    }
```

**Comment by kfung0426** [comment]
Hi tilltue, thanks for your reply.
I know I can change the file there.
The matter appears when I "pod update" your library, my revised code will be replaced.
I forgot to change it back and submitted to App Store...I need to make another update now.

So I ask for a declare place apart from the core code.

**Comment by tilltue** [comment]
@kfung0426 
Oh i see.
I mean, you can extension method in your project.
But now, I added parameter PHVideoRequestOptions at exportVideoFile method.

**Comment by kfung0426** [comment]
thanks for your update

**Comment by kfung0426** [comment]
oops, could you please also add for the tempCopyMediaFile()?

**Comment by kfung0426** [comment]
Hi tilltue,
thanks for your update. I'm sorry that I haven't tell you clearly and make you misunderstood.

Actually, I am asking for the change "AVAssetExportPresetHighestQuality" to "AVAssetExportPresetPassthrough" in the line:180 


 return PHImageManager.default().requestExportSession(forVideo: phAsset, options: requestOptions, exportPreset: AVAssetExportPresetHighestQuality) { (session, infoDict) in

to 

 return PHImageManager.default().requestExportSession(forVideo: phAsset, options: requestOptions, exportPreset: AVAssetExportPresetPassthrough) { (session, infoDict) in

could you please make AVAssetExportPresetPassthrough can pass to tempCopyMediaFile() ?

**Comment by tilltue** [comment]
I've added for that. :)

**Comment by kfung0426** [comment]
awesome, thank you
