### ISSUE TITLE
Swift Compiler Error Group

### ISSUE THREAD

**Issue by fuuqiu** [tilltue/TLPhotoPicker#116]
<unknown>:0: error: fatal error encountered while reading from module 'medicine'; please file a bug report with your project and the crash log

*** DESERIALIZATION FAILURE (please include this section in any bug report) ***
top-level value not found
Cross-reference to module 'TLPhotoPicker'
... TLPhotosPickerViewControllerDelegate

0  swift                    0x0000000112a30ffa PrintStackTraceSignalHandler(void*) + 42
1  swift                    0x0000000112a303b6 SignalHandler(int) + 966
2  libsystem_platform.dylib 0x00007fff64132f5a _sigtramp + 26
3  swift                    0x00000001133a7900 (anonymous namespace)::DarwinX86AsmBackend::getCompactUnwindRegNum(unsigned int) const::CU32BitRegs + 103838
4  libsystem_c.dylib        0x00007fff63ed01ae abort + 127
5  swift                    0x000000011015ebae swift::ModuleFile::fatal(llvm::Error) + 2062
6  swift                    0x000000011016c84c swift::ModuleFile::getDeclCheckedImpl(llvm::PointerEmbeddedInt<unsigned int, 31>, llvm::Optional<swift::DeclContext*>) + 55004
7  swift                    0x000000011015f03f swift::ModuleFile::getDeclChecked(llvm::PointerEmbeddedInt<unsigned int, 31>, llvm::Optional<swift::DeclContext*>) + 79
8  swift                    0x000000011016e9df swift::ModuleFile::getTypeChecked(llvm::PointerEmbeddedInt<unsigned int, 31>) + 3759
9  swift                    0x00000001101705bc swift::ModuleFile::getTypeChecked(llvm::PointerEmbeddedInt<unsigned int, 31>) + 10892
10 swift                    0x000000011017fe17 swift::SILDeserializer::readSILFunction(llvm::PointerEmbeddedInt<unsigned int, 31>, swift::SILFunction*, llvm::StringRef, bool, bool) + 455
11 swift                    0x000000011019421d swift::SILDeserializer::getAllSILFunctions() + 893
12 swift                    0x000000011022ca84 swift::SerializedSILLoader::getAllForModule(swift::Identifier, swift::FileUnit*) + 196
13 swift                    0x000000010f08efeb performCompile(swift::CompilerInstance&, swift::CompilerInvocation&, llvm::ArrayRef<char const*>, int&, swift::FrontendObserver*, swift::UnifiedStatsReporter*) + 30459
14 swift                    0x000000010f085e64 swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) + 7908
15 swift                    0x000000010f03a8b5 main + 18917
16 libdyld.dylib            0x00007fff63e24015 start + 1
Stack dump:

**Comment by tilltue** [comment]
This error is from the Swift compiler, asking you to file a bug report against the compiler. There's not much i can do about a Swift compiler bug.

https://swift.org/contributing/#reporting-bugs
