### ISSUE TITLE
Delegate-Methods are not called after taking new photo

### ISSUE THREAD

**Issue by AWeleczka** [tilltue/TLPhotoPicker#117]
It seems the photo picker looses connection to its delegates when a new photo is taken.

The new picture is highlighted in the camera roll but the `selectedCameraCell(picker: TLPhotosPickerViewController)` nor the `deselectedPhoto(picker: TLPhotosPickerViewController, at: Int)` method never fire, not even when selecting additional images.  
When confirming the image-selection now none of the expected methods `dismissPhotoPicker(withPHAssets: [PHAsset])` or `dismissPhotoPicker(withTLPHAssets: [TLPHAsset])` fire and the picker dismisses too far. 
(dismissing  the presented view presenting the picker, throwing the user out of a menu)

**Reproduction-Steps:**
- present a TLPhotosPickerViewController
- Tap Camera-Icon
- Take a picture and use it

This issue was seen on a physical iPhone 6 with iOS 11.3 and TLPhotoPicker 1.6.8 through CocoaPods.

**Comment by tilltue** [comment]
@AWeleczka 
I think it should work now. I've pushed a fix for this.

1.6.9 Release
------------------------------------------------------------
Bug Fix : selectedCameraCell when use custom camera cell.
And the 'TLPhotopicker' call log delegate method selectedPhoto when photo use it.

**Comment by AWeleczka** [comment]
@tilltue I just upgraded to 1.6.9 and don't see any change.

I checked to make sure the changes are in the pods in the project after updating, cleaned, build and reinstalled the app on the device with the same outcome as before.

After the camera has been used the delegate-methods `selectedPhoto(picker: TLPhotosPickerViewController, at: Int)` `deselectedPhoto(picker: TLPhotosPickerViewController, at: Int)` and `dismissPhotoPicker(withPHAssets: [PHAsset])` (these are the ones I use) don't fire. `selectedCameraCell(picker: TLPhotosPickerViewController)` does fire when tapping the camera-cell (as it did previously already).

I looked a bit deeper into the issue on my end and found out that `tlpicker.modalPresentationStyle = .overCurrentContext` is the reason for the delegate-methods not firing - yet without the presentation style the picker always shows the unwanted navigation-behavior of dismissing the entire view below it.

Navigation-structure is  
Base --PushToNavigationStack--> CreateView --Present--> TLPhotoPicker

**Comment by tilltue** [comment]
@AWeleczka 
It's working.

Testing Example 

https://github.com/tilltue/TLPhotoPicker/tree/master/Example
line30 :  viewController.modalPresentationStyle = **.overCurrentContext**
               viewController.logDelegate = self

TLPhotosPickerLogDelegate
--- Log
selectedCameraCell
selectedPhoto
selectedCameraCell
deselectedPhoto
selectedCameraCell

![lhhy7242](https://user-images.githubusercontent.com/2108446/40425200-a206d2b4-5ed2-11e8-9400-fd8b81f69770.gif)
