### ISSUE TITLE
Hello If the selected image is in 'iCloud'

### ISSUE THREAD

**Issue by fuuqiu** [tilltue/TLPhotoPicker#119]
Hello If the selected image is in 'iCloud', then how do I get the TLPPHites of the selected photo?

**Comment by tilltue** [comment]
https://github.com/tilltue/TLPhotoPicker/issues/29

If you can't find what you want check this issues list.

https://github.com/tilltue/TLPhotoPicker/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+icloud
