### ISSUE TITLE
Feature: Single photo select

### ISSUE THREAD

**Issue by tnylee** [tilltue/TLPhotoPicker#126]
First, thank you for such a great library. I've been using it for sometime without any problems.

My app is using `TLPhotoPicker` with `singleSelectedMode` turned on. The app requires users to select only 1 image at a time. Right now users have to select an image and press Done to navigation to another controller.

Is it possible to bring the user to another controller immediately without having to press the Done button? Meaning, once the user pressed an image, `TLPhotosPickerViewController` dismisses and `didFinishPickingMediaWithInfo` gets called immediately.

**Comment by tilltue** [comment]
@tnylee
Here's one simple solution to choose one image a time.
```swift
class CustomPhotoPickerViewController: TLPhotosPickerViewController {
    override func makeUI() {
        super.makeUI()
        self.customNavItem.leftBarButtonItem = UIBarButtonItem.init(barButtonSystemItem: .stop, target: nil, action: #selector(customAction))
    }
    @objc func customAction() {
        self.dismiss(animated: true, completion: nil)
        
    }
    override func collectionView(_ collectionView: UICollectionView, didSelectItemAt indexPath: IndexPath) {
        super.collectionView(collectionView, didSelectItemAt: indexPath)
        if selectedAssets.count == 1 {
            self.doneButtonTap()
        }
    }
}

```

```swift
        let viewController = CustomPhotoPickerViewController()
        viewController.delegate = self
        var configure = TLPhotosPickerConfigure()
        configure.numberOfColumn = 3
        configure.doneTitle = ""
        viewController.configure = configure
        self.present(viewController, animated: true, completion: nil)
```

**Comment by tnylee** [comment]
Works great! Thanks!
