### ISSUE TITLE
Customize navigationBar Appearance

### ISSUE THREAD

**Issue by Urkman** [tilltue/TLPhotoPicker#131]
Hi,

what is the best way to customize the navigationaBar Appearance?

Thanks,
Urkman

Here is an Image of my iPhoneX:
<img width="387" alt="bildschirmfoto 2018-08-27 um 13 24 22" src="https://user-images.githubusercontent.com/94297/44657300-a7fc9080-a9fc-11e8-8746-b24232d9abbf.png">

**Comment by Urkman** [comment]
Found a way by extending TLPhotosPickerViewController...
But perhaps there is an other way?

`
class PickerViewController: TLPhotosPickerViewController {    

    override var preferredStatusBarStyle: UIStatusBarStyle {
        return .lightContent
    }
    
    override func makeUI() {
        super.makeUI()
        
        self.titleLabel.textColor = UISettings.headerTextColor
        self.subTitleLabel.textColor = UISettings.headerTextColor
        self.view.backgroundColor = UISettings.headerBackgroundColor
    }
}
`

**Comment by tilltue** [comment]
@Urkman  
Hi
I know that is not convenient customization in navigation bar.

Is this what you want?
![simulator screen shot - iphone x - 2018-08-28 at 07 21 38](https://user-images.githubusercontent.com/2108446/44690280-31f83800-aa95-11e8-9ad6-461f19d13155.png)

I create a new branch, with used black style pickerViewController.
https://github.com/tilltue/TLPhotoPicker/tree/black_style

If this answer is what you want, i will update version.
thx.
