### ISSUE TITLE
Crash!!!

### ISSUE THREAD

**Issue by Nick-Ace** [tilltue/TLPhotoPicker#132]
App crashes when older pictures are selected. 
When image /assests older than a month or so are selected it crashes whil trying to return fullresolutionimage from TLPhassets.

**Comment by tilltue** [comment]
@Nick-Ace 
Can you share a complete crash log from the crash?

**Comment by Nick-Ace** [comment]
var tempImage = [UIImage]()
if withTLPHAssets.count != 0 {
            for items in withTLPHAssets{
                tempImage.append(items.fullResolutionImage!)
            }
 }
It crashes while trying to return the fullResolution image.
This what  I get if I  print items which is of type TLPHAsset
Optional(<PHAsset: 0x10cd3c020> CC8C1F60-DAD9-4598-899B-77780FB3AADE/L0/001 mediaType=1/0, sourceType=1, (3024x4032), creationDate=2018-09-05 00:32:11 +0000, location=1, hidden=0, favorite=0 ), selectedOrder: 1)

**Comment by milo157** [comment]
The reason this happens is because the images from a few months back are not stored locally on the device but on your iCloud account. It therefore crashes since technically the object doesn't exist on your device. You would manually have to download the image and then selected it.

**Comment by Nick-Ace** [comment]
@milo157  it seems you are right could you point be to a direction to work form, does ttlpicker provide any such methods to do so ? how do i make it work !

**Comment by milo157** [comment]
@Nick-Ace Sorry I didn't get back to you. Find below a solution to your problem:

func downloadICloudImage(asset: PHAsset, completionHandler: @escaping (Bool, UIImage) -> ()) {
        let manager = PHImageManager.default()
        let requestOptions = PHImageRequestOptions()
        requestOptions.resizeMode = .exact
        requestOptions.deliveryMode = .highQualityFormat;
        
        // Request Image
        manager.requestImage(for: asset, targetSize: CGSize(width: 1500.0, height: 900.0), contentMode: .aspectFill, options: requestOptions) { (result, _) in
    
            completionHandler(true, result!)
        }
    }
