### ISSUE TITLE
Gallery not refreshing after taking a photo

### ISSUE THREAD

**Issue by fralways** [tilltue/TLPhotoPicker#134]
Hi, 

Im having an issue with iPhoneX - when I take a photo with it gallery doesn't refresh, and I need to take one or two more photos and then it starts refreshing. On iPhone 6s this works great, but on iPhoneX it doesn't get updated right away. Unfortunately I cannot send any logs from it since I do not own iPhoneX and simulator doesn't have camera, but on my review sessions, testers have it and they observe this bug. 
I tried default cameraCell and dynamic one (from the example) and results are the same in both cases.

**Comment by tilltue** [comment]
@fralways 
It works fine on my iPhone X.
![img_4318](https://user-images.githubusercontent.com/2108446/45702356-97c77380-bbac-11e8-9c10-c7dffe5a0280.gif)

Is there anything I missed?

**Comment by fralways** [comment]
Very strange! It works perfectly for you. I will try to investigate more and see if I can get any findings why it doesn't work for me. Thanks for taking your time to check this.

**Comment by rizwan95** [comment]
@fralways : Can you please specify your OS version, the device model in which you tested it and the Xcode which you used to build the library?

**Comment by fralways** [comment]
@rizwan95 iOS 12, iPhoneX, Xcode 10.
Btw, I have observed that when user takes camera shot, and then clicks done, that image is passed to the delegate. So the image is there, just the collection view in gallery isnt refreshing.

**Comment by rizwan95** [comment]
I will try to reproduce it and get back to you.
