### ISSUE TITLE
Override UIView property warning

### ISSUE THREAD

**Issue by jay10447** [tilltue/TLPhotoPicker#136]
The Override UIView property func in "TLPhotoCollectionViewCell.swift" has warning with swift4.2.

change:

override open static var layerClass: AnyClass {
    return AVPlayerLayer.self
}

to

override final public class var layerClass: AnyClass {
    return AVPlayerLayer.self
}

**Comment by tilltue** [comment]
@jay10447 

I've pushed a fix for this  d816348748f280324524fd514cce180baf0d19f5

```swift4
override open class var layerClass: AnyClass {
        return AVPlayerLayer.self
    }
```
