### ISSUE TITLE
*** error reading settings archive file

### ISSUE THREAD

**Issue by shancer46** [tilltue/TLPhotoPicker#137]
when you click on Show Picker , i am getting following error 
but it is working , i am able to select the images , there is no problem there 
do you have any idea about it?

2018-09-20 22:54:59.392874+0300 TLPhotoPicker_Example[30557:21883484] 
*** error reading settings archive file: <ISRootSettings: /Users/selahattinhancer/Library/Developer/CoreSimulator
/Devices/203B49C7-6FA3-4370-9E5D-DF56DB9E5D7B/data/Containers/Data/Application/EF25020F-BC81-403D-9C76-916750E040AC
/Documents/org.cocoapods.demo.TLPhotoPicker-Example.settings/ISRootSettings_10.plist>

**Comment by tilltue** [comment]
@shancer46 
https://stackoverflow.com/questions/36686835/error-reading-settings-archive-file-isrootsettings
🧐I will check that.

**Comment by tilltue** [comment]
@shancer46 
The reason for the error is that it used PHLivePhotoView.
I tested simple new example.
```swift4
import UIKit
import PhotosUI

class ViewController: UIViewController {
    var test:PHLivePhotoView? = nil
    override func viewDidLoad() {
        super.viewDidLoad()
        self.test = PHLivePhotoView(frame: self.view.frame)
        // Do any additional setup after loading the view, typically from a nib.
    }
}
```
same error.
```
2018-09-22 00:04:22.101268+0900  *** error reading settings archive file: <ISRootSettings: /var/mobile/Containers/Data/Application/CC5BC005-21E7-4BF2-927B-FB31E59E7496/Documents/tilltue.Test.settings/ISRootSettings_11.plist>
```
My guess is, that would be PhotosUI framework bug.
As you know, this error does not cause any issue in the App's function.

**Comment by shancer46** [comment]
ok  thank  you very much   for clarification
