### ISSUE TITLE
Example code : cloudImageDownload fails to load image data asset

### ISSUE THREAD

**Issue by jtressle** [tilltue/TLPhotoPicker#140]
Hi there,

I'm using Xcode 10.0, iOS12, an iPhone X, and am encountering an issue where cloudImageDownload is unable to download a PHAsset.

This is the error I'm getting:

> 2018-09-22 13:39:34.861134-0700 TLPhotoPicker_Example[32314:4161422] [Generic] Failed to load image data for asset <PHAsset: 0x10bb49430> 41C9AE3F-1CD4-437F-95C6-A954515DAA25/L0/001 mediaType=1/0, sourceType=1, (6000x4000), creationDate=2018-07-03 23:40:04 +0000, location=0, hidden=0, favorite=0  with format 9999

Thanks!

**Comment by tilltue** [comment]
@jtressle 
https://forums.developer.apple.com/thread/16244#293509
My guess is it will be successful if you deliver the size to the parameter. 
Can you try this?
```swift
let size = CGSize(width: w * 0.5, height: h * 0.5)
cloudImageDownload(asset: asset, size: size, ... )
```
If this fails, PHImageRequestOptions is a problem caused by different things, so I will add PHImageRequestOptions to the cloudImageDownload function parameters.

```swift
class func cloudImageDownload(asset: PHAsset, options: PHImageRequestOptions? = nil, size: CGSize = PHImageManagerMaximumSize, progressBlock: @escaping (Double) -> Void, completionBlock:@escaping (UIImage?)-> Void ) -> PHImageRequestID {
        var options = options
        if options == nil {
            options = PHImageRequestOptions()
            options?.isSynchronous = false
            options?.isNetworkAccessAllowed = true
            options?.deliveryMode = .opportunistic
            options?.version = .current
            options?.resizeMode = .exact
            options?.progressHandler = { (progress,error,stop,info) in
                progressBlock(progress)
            }
        }
        let requestId = PHCachingImageManager().requestImageData(for: asset, options: options) { (imageData, dataUTI, orientation, info) in
            if let data = imageData,let _ = info {
                completionBlock(UIImage(data: data))
            }else{
                completionBlock(nil)//error
            }
        }
        return requestId
    }
```

**Comment by jtressle** [comment]
@tilltue thanks for the response.  Looks like it might be an iCloud caching issue.  I added the size parameter, and download worked.  However, I also reran your original code and that works too.

So, maybe close this issue for now?  I'm unable to reproduce the issue again.  Also, the link you attached points to an Apple bug.

Thanks!
