### ISSUE TITLE
Done button enabled?

### ISSUE THREAD

**Issue by hhoangna** [tilltue/TLPhotoPicker#142]
I want to make done button enabled when i have photos was selected and disabled when i have no photo selected like Facebook. 
How can I do that?

**Comment by tilltue** [comment]
@hhoangna 
My guess is this is what you want.
```swift
class CustomPhotoPickerViewController: TLPhotosPickerViewController {
    override func makeUI() {
        super.makeUI()
        self.customNavItem.leftBarButtonItem = UIBarButtonItem.init(barButtonSystemItem: .stop, target: nil, action: #selector(customAction))
        self.doneButton.isEnabled = self.selectedAssets.count > 0
    }
    @objc func customAction() {
        self.dismiss(animated: true, completion: nil)
    }
    override func collectionView(_ collectionView: UICollectionView, didSelectItemAt indexPath: IndexPath) {
        super.collectionView(collectionView, didSelectItemAt: indexPath)
        self.doneButton.isEnabled = self.selectedAssets.count > 0
    }
}
```

**Comment by hhoangna** [comment]
omg. I forgot this line:
super.collectionView(collectionView, didSelectItemAt: indexPath)
Thanks so much!

**Comment by Smiller193** [comment]
Disabling the done button doesn't work for me

**Comment by vuhomobytelab** [comment]
it does not enable when I captured from the camera

**Comment by tilltue** [comment]
@vuhomobytelab 
You can use 'TLPhotosPickerLogDelegate' and check selected assets count.

TLPhotosPickerLogDelegate
func selectedPhoto(picker: TLPhotosPickerViewController, at: Int)
