### ISSUE TITLE
Limit Number of Different Media Type Selections

### ISSUE THREAD

**Issue by deanjamesss** [tilltue/TLPhotoPicker#153]
Great repo! Currently using it in an iOS application thats under development. Just a quick question - I know there is functionality to limit the total selection number, but is there scope to say limit the user to selecting X number of videos and Y number of photos? Or can only the total number of selections be limited?

Thanks for your help!

**Comment by tilltue** [comment]
Thank you @deanjamesss  😄 

You can customizable limited selection count, what you want.
https://github.com/tilltue/TLPhotoPicker/commit/3ea562f657df83a6566c52d6bcec2573b8235acd

**Comment by deanjamesss** [comment]
Awesome! Thank you so much! :)
