### ISSUE TITLE
Ability to add date section

### ISSUE THREAD

**Issue by MrFuFuFu** [tilltue/TLPhotoPicker#154]
![50709913_1646877092079392_4364811650440626176_n](https://user-images.githubusercontent.com/6850766/51431896-269be800-1c94-11e9-8d82-60f0fe014fb8.png)

Hi, Just wondering, Can `TLPhotoPicker` add Date section for different days? 
Cheers

**Comment by tilltue** [comment]
I would try it. But My guess is It will take about few days.

**Comment by MrFuFuFu** [comment]
Thanks. Don't worry, take your time.

**Comment by tilltue** [comment]
@MrFuFuFu 
https://github.com/tilltue/TLPhotoPicker/releases/tag/1.8.1
Now, You can used custom supplement view and grouped by date for assets collection.

Look at this example "with Custom Layout"

Preview
![simulator screen shot - iphone x - 2019-01-24 at 00 41 59](https://user-images.githubusercontent.com/2108446/51618081-eaf16e80-1f70-11e9-8ef8-7342030c6fdd.png)

**Comment by MrFuFuFu** [comment]
Absolutely fast!!! Thanks, very appreciate.

**Comment by tilltue** [comment]
@MrFuFuFu 
Sorry 1.8.1 version has critical bug. I've fixed that in 1.8.2.
https://github.com/tilltue/TLPhotoPicker/commit/96f706e1df3401bebcc96064e55e5cd509bd59c0
