### ISSUE TITLE
Please tell me can I Disable playback video?

### ISSUE THREAD

**Issue by dev3ios** [tilltue/TLPhotoPicker#16]
Please tell me can I Disable playback video?

**Comment by tilltue** [comment]
@dev3ios 
https://github.com/tilltue/TLPhotoPicker/blob/master/Example/TLPhotoPicker/CustomCell_Instagram.swift

use custom cell. 
playerView is optional properties.

```swift
open class TLPhotoCollectionViewCell: UICollectionViewCell {
    @IBOutlet open var imageView: UIImageView?
    @IBOutlet open var playerView: TLPlayerView?
//...
}
```

**Comment by jimsmithm3** [comment]
@tilltue  Can you provide some more detail on what to set?  I have tried making player and playerView both nil without any luck.  

I just want the video to not play when I select the cell.

**Comment by tilltue** [comment]
@jimsmithm3 
```swift
open class TLPhotoCollectionViewCell: UICollectionViewCell {
    @IBOutlet open var imageView: UIImageView?
    @IBOutlet open var playerView: TLPlayerView? //<- you don't want to play? remove this.
//...
}
```
