### ISSUE TITLE
Remove some selectedItems, then show picker, it will show missed number

### ISSUE THREAD

**Issue by baryon** [tilltue/TLPhotoPicker#160]
In my code, 
```
self.selectedAssets.remove(at: 0)
self.selectedAssets.remove(at: 1)
self.selectedAssets.remove(at: 3)

```
then show picker with selectedAssets
```
        viewController.selectedAssets = self.selectedAssets
        self.present(viewController, animated: true, completion: nil)

```
Result:

![simulator screen shot - iphone x - 2019-02-07 at 20 33 19](https://user-images.githubusercontent.com/421757/52409098-ccb27380-2b17-11e9-85cb-f6cc5c8fcc53.png)

**Comment by tilltue** [comment]
@baryon 
Try this.
https://github.com/tilltue/TLPhotoPicker/issues/138
