### ISSUE TITLE
Firebase Video To Phasset to TLPHAsset

### ISSUE THREAD

**Issue by Smiller193** [tilltue/TLPhotoPicker#162]
First I would like to say thank you for this library it allowed me to create a custom UI component that a couple people are currently using. I use this app to create a custom row in a form data UI where a user can use this custom row to select a video from there phone and upload it to a server such as firebase.

My issue now comes with editing the video on the server. When the user selects the collection of information it is loaded from there server incase the user wants to either edit it or keep it the same.

I already read the documentation and understand that I can download a video from firebase to my phone.

But how would I change that into a phAsset and then a TLPhasset so I can place it in the user can see that there current video is indeed on the server. The picture is an example of the UI that I have. I can put the image there but not the video.

<img width="333" alt="screen shot 2019-02-13 at 3 07 04 pm" src="https://user-images.githubusercontent.com/16108750/52740467-1a5c2f80-2fa1-11e9-94c2-f3e82491bc94.png">

**Comment by tilltue** [comment]
@Smiller193 
PHAsset is an object for a photo library. 
Converting local video or images to PHAsset is not matched with actual data. 
So, Not available in this library.
