### ISSUE TITLE
How to append image from uiImage

### ISSUE THREAD

**Issue by shoesboy** [tilltue/TLPhotoPicker#163]
hi master!

i want when i take a picture, append picker.selectedasset.

my code,

if let image = (uImg as? UIImage) {
                var placeholderAsset: PHObjectPlaceholder? = nil
                PHPhotoLibrary.shared().performChanges({
                    let newAssetRequest = PHAssetChangeRequest.creationRequestForAsset(from: image)
                    placeholderAsset = newAssetRequest.placeholderForCreatedAsset
                }, completionHandler: { [weak self] (sucess, error) in
                    if sucess, let `self` = self, let identifier = placeholderAsset?.localIdentifier {
                        guard let asset = PHAsset.fetchAssets(withLocalIdentifiers: [identifier], options: nil).firstObject else { return }
                        
                        var result = TLPHAsset(asset: asset)
                        result.selectedOrder = self.picker.selectedAssets.count + 1
                        self.picker.selectedAssets.append(result)
                        self.picker.logDelegate?.selectedPhoto(picker: self.picker, at: 0)
                    }
                })
            }

but TLPHAsset's init function is internal protection level, so error 
help me plz

**Comment by tilltue** [comment]
@shoesboy 
My Guess is you can used this
TLPHAsset.asset(with: asset.localIdentifier)

```swift3

public static func asset(with localIdentifier: String) -> TLPHAsset? {
        let fetchResult = PHAsset.fetchAssets(withLocalIdentifiers: [localIdentifier], options: nil)
        return TLPHAsset(asset: fetchResult.firstObject)
    }
```

**Comment by shoesboy** [comment]
@tilltue thx for you reply
but this issue can acess TLPHAsset 

TLPHAsset need initializer but TLPHAsset's init() function protection level
so in my code, can use TLPHAsset..

I am the first ios project
So I might not know it, so let me know if there's a way around this.

thank you very much 

<img width="955" alt="2019-02-23 2 31 07" src="https://user-images.githubusercontent.com/2166803/53259918-ad206b00-3713-11e9-9fe0-b03e6499d934.png">

**Comment by tilltue** [comment]
@shoesboy 
I don't understand. You can just used that.
https://github.com/tilltue/TLPhotoPicker/blob/master/TLPhotoPicker/Classes/TLAssetsCollection.swift
275 line.

**Comment by shoesboy** [comment]
@tilltue oh i'm sorry i'm understand!! thx
