### ISSUE TITLE
Live camera play

### ISSUE THREAD

**Issue by riccarena** [tilltue/TLPhotoPicker#164]
If I scroll in my photo library at second line of collection, and then I return at the first, the cell with a live camera doesn't start.

 I have to scroll under the second line and then scroll to the first for start it.

When I click on cell with camera the error is this: 
`Error capturing photo: Error Domain=AVFoundationErrorDomain Code=-11803 "Impossible to register" UserInfo={NSLocalizedRecoverySuggestion=Try to register again., NSLocalizedDescription=Impossible to register, NSUnderlyingError=0x283e7c030 {Error Domain=NSOSStatusErrorDomain Code=-16409 "(null)"}}`

**Comment by tilltue** [comment]
@riccarena 
Maybe [relevant issue ](https://github.com/tilltue/TLPhotoPicker/issues/171)
I can't reproduce it.

**Comment by riccarena** [comment]
@tilltue 
There is the error also with the new version. I zip a screen recording with it.
[ScreenRecording_04-01-2019 11-03-13.MP4.zip](https://github.com/tilltue/TLPhotoPicker/files/3028509/ScreenRecording_04-01-2019.11-03-13.MP4.zip)

**Comment by tilltue** [comment]
I think it should work now. I've pushed a fix for this. 
release 1.8.9
