### ISSUE TITLE
Xcode 10.2 fail

### ISSUE THREAD

**Issue by Hilalkah** [tilltue/TLPhotoPicker#169]
When i update xcode to 10.2 this error has been appear when i scroll in photo library.

`Thread 1: EXC_BAD_ACCESS (code=1, address=0x18)`

This line (line 900) : 

> if self.requestIds[indexPath] != nil { 

in TLPhotosPickerViewController.swift

**Comment by tilltue** [comment]
@mbarashkov has put together #168 to address this issue.
@Hilalkah can you verify that?

**Comment by Hilalkah** [comment]
Thanks, it's solved.
