### ISSUE TITLE
How to use embedded in a ViewController

### ISSUE THREAD

**Issue by rankinit** [tilltue/TLPhotoPicker#17]
I would like to use the TLPhotoPicker in a ViewController within a defined view frame instead of modal display in a separate ViewController.   I think what I would like is to use the TLAlbumPopView in a view container in the ViewController that I'm developing.

The result I'm looking for is to have 2 main views on the ViewController. One that will display the results of what the user picked (plus some other features) and the Album view.

I tried embedding the TLPhotosPickerViewController in the ViewController but the images were small and blurry. Plus the nav bar is also embedded.  Just curious on how I can use the TLAlbumPopView or embed the TLPhotosPickerViewController with some customization.

**Comment by tilltue** [comment]
sorry. i have no idea.
if you want to embedded in a viewcontroller, you have to customization TLPhotoPickerViewController.
