### ISSUE TITLE
Select assets before showing picker

### ISSUE THREAD

**Issue by intoxicated** [tilltue/TLPhotoPicker#170]
TLPhotosPickerViewController has selectedAssets but I don't think it was made to accept assets from outside. Is there a way to display picker with selectedAssets?

**Comment by tilltue** [comment]
See [this issue](https://github.com/tilltue/TLPhotoPicker/issues/163)

**Comment by intoxicated** [comment]
Got it, I was trying to set selectedAssets = someNewAccests instead of `append:` operator
