### ISSUE TITLE
Crash when navigating into video category

### ISSUE THREAD

**Issue by intoxicated** [tilltue/TLPhotoPicker#171]
<img width="1401" alt="Screen Shot 2019-03-30 at 11 37 05 AM" src="https://user-images.githubusercontent.com/848531/55270268-32350c00-52e0-11e9-977f-940f8036b9ec.png">

I'm not entirely sure what causes this issue but I'm still looking into it. Basically the crash happened inside Apple's framework (hint from __NSTaggedDate, first time was NSIndexPath), something went wrong while requesting images on video tap.  

I'm using Xcode 10.2, iOS 12.1, iPhone XS

**Comment by intoxicated** [comment]
After some quick debug, quene.async -> DispatchQueue.main.async causes the issue. This crash didn't happen once I commented out queue.async and DispatchQueue.main.async. So my wild guess is some part of code does not handle properly while working on different thread..

**Comment by intoxicated** [comment]
I thought it was only on video category but apparently it also happens on photo category if you try to scroll up and down on multiple times. 

I suspect that exception reason: `[someRandomeObject objectForKey:]` indicates that `if self.requestIds[indexPath] != nil` line which variable requestIds memory address somehow get corrupted and its pointer address some other object in Apple's framework lol.. I thought it could be temporary so I did delete application and clean build again, but same thing happened. 

Removing that line stopped the crash so far.

**Comment by tilltue** [comment]
Thank you so much. @intoxicated , @mbarashkov
I think it should work now. I've pushed a fix for this. a42179b909ab3283ae2275092e76b99eeb8a814f
version 1.8.5 
Can you verify it?

**Comment by nitinumaretiya123** [comment]
while presenting TLPhotosPickerViewController crashed. got issue after update pod for swift 5
`"Attempt to use unknown class"`
