### ISSUE TITLE
Dark Mode please?

### ISSUE THREAD

**Issue by MrFuFuFu** [tilltue/TLPhotoPicker#172]
Hi I'm here again.

Would you like to consider adding Dark Mode feature? 

Or we can configure the colors.

**Comment by tilltue** [comment]
@MrFuFuFu 
Check this.
https://github.com/tilltue/TLPhotoPicker/tree/black_style

**Comment by MrFuFuFu** [comment]
Hi thank you, will give it a try soon. Any plan to merge this branch to the master if this feature works well?

**Comment by tilltue** [comment]
@MrFuFuFu  Sure!

**Comment by MrFuFuFu** [comment]
Hi @tilltue I had a look of this branch and it looks great. Any plan to merge to release this part? Will be very happy to update into our app.

**Comment by tilltue** [comment]
@MrFuFuFu 
I'll do it soon. 😄

**Comment by tilltue** [comment]
https://github.com/tilltue/TLPhotoPicker/releases/tag/1.8.8
