### ISSUE TITLE
app crash when scrolling in TLPhotosPickerViewController

### ISSUE THREAD

**Issue by morrischen** [tilltue/TLPhotoPicker#177]
App crash when scrolling top and down in TLPhotosPickerViewController.

My pod version is Release 1.8.4 with swift 5, please help.

Here is my code:

![螢幕快照 2019-04-17 下午5 49 38](https://user-images.githubusercontent.com/17924106/56278649-31520600-6139-11e9-8a73-bcb3fb3b32f3.png)
![螢幕快照 2019-04-17 下午5 50 26](https://user-images.githubusercontent.com/17924106/56278734-5777a600-6139-11e9-81eb-ec31a477d073.png)

error message:

![螢幕快照 2019-04-17 下午5 47 26](https://user-images.githubusercontent.com/17924106/56278496-ea641080-6138-11e9-8292-1ee44215448d.png)

**Comment by tilltue** [comment]
My guess is it's like same [this issue](https://github.com/tilltue/TLPhotoPicker/issues/171). please check this.

**Comment by morrischen** [comment]
@tilltue 
Thank for your help, i was pod for new version 1.8.6 and rebuild the project.

TLPhotoPickerViewController is work fine now when scrolling, but i'm not sure, i will keep this issue if this bugs happened again.
