### ISSUE TITLE
Error using Carthage and Xcode 10.2

### ISSUE THREAD

**Issue by unpluggedk** [tilltue/TLPhotoPicker#178]
Has this been tested? I see a build input file cannot be found error
... /Carthage/Checkouts/TLPhotoPicker/Example/Pods/Target Support Files/TLPhotoPicker/ResourceBundle-TLPhotoPicker-TLPhotoPicker-Info.plist'

**Comment by tilltue** [comment]
@unpluggedk 
I think it should work now. I've pushed a fix for this.
carthage version 1.8.7
https://github.com/tilltue/TLPhotoPicker/commit/1fbc4a2b0f9f4d2306032e42b7cee18718cddcf0
