### ISSUE TITLE
Stop saving photos/videos taken with camera to the library

### ISSUE THREAD

**Issue by juanpablofernandez** [tilltue/TLPhotoPicker#179]
Is there a way to stop saving the assets taken with the camera to the photos library? I'd like for them to be returned as a TLPHAsset but not saved to the device library. Many thanks!

**Comment by tilltue** [comment]
@juanpablofernandez 
[Override this function](https://gist.github.com/tilltue/7248923dd3d8fd4a859007e7ea0a82ef)
But TLPHAsset need to PHAsset. For this reason, you have to handle the image without TLPHAsset.

**Comment by juanpablofernandez** [comment]
Many thanks!
