### ISSUE TITLE
convert selected Assets to UIImageView

### ISSUE THREAD

**Issue by aqeelhashem** [tilltue/TLPhotoPicker#18]
thanks for great extension,
my question, how can convert the selected images to array of UIImage then to UIImageView ?

**Comment by aqeelhashem** [comment]
I using this code in ( dismissPhotoPicker ) function , but it get me all images in studio not what i selected 

`    
    var images:NSMutableArray = NSMutableArray()

    func dismissPhotoPicker(withPHAssets: [PHAsset]) {
        // if you want to used phasset.
        
     
        let imgManager = PHImageManager.default()
        
        let requestOptions = PHImageRequestOptions()
        requestOptions.isSynchronous = true
        requestOptions.deliveryMode = .highQualityFormat
        
        let fetchOptions =  PHFetchOptions()
        fetchOptions.sortDescriptors = [NSSortDescriptor(key: "creationDate",ascending: false)]
        
        if let fetchResult : PHFetchResult = PHAsset.fetchAssets(with: .image, options: fetchOptions) {
            
            if fetchResult.countOfAssets(with: PHAssetMediaType.image) > 0 {
                for i in 0..<fetchResult.count {
                    
                    imgManager.requestImage(for: fetchResult.object(at: i) as PHAsset, targetSize: CGSize(width: 300, height: 300), contentMode: .aspectFill, options: requestOptions, resultHandler: { (image, error) in
                        self.images.add(image!)

                    })

             
                }
                self.mycollection.reloadData()
 
            }
        }
 
 
 
    }`

**Comment by tilltue** [comment]
hi @aqeelhashem 
used this code.

```swift
    var images = [UIImage]()
    
    func dismissPhotoPicker(withTLPHAssets: [TLPHAsset]) {
        let imageManager = PHCachingImageManager()
        let options = PHImageRequestOptions()
        options.deliveryMode = .opportunistic
        options.isNetworkAccessAllowed = true
        
        let size = CGSize(width: 300, height: 200)
        let assets = withTLPHAssets.flatMap{ $0.phAsset }
        for asset in assets {
        imageManager.requestImage(for: asset, targetSize: size, contentMode: .aspectFill, options: options) { [weak self] image, info in
            guard let image = image else { return }
            self?.images.append(image)
        }
    }
```

**Comment by aqeelhashem** [comment]
Thanks very much, great work

I just added this code to prevent duplicate images when editing:

        images.removeAll()

and this final:

 var images = [UIImage]()
    
    func dismissPhotoPicker(withTLPHAssets: [TLPHAsset]) {
        images.removeAll()
        let imageManager = PHCachingImageManager()
        let options = PHImageRequestOptions()
        options.deliveryMode = .opportunistic
        options.isNetworkAccessAllowed = true
        
        let size = CGSize(width: 300, height: 200)
        let assets = withTLPHAssets.flatMap{ $0.phAsset }
        for asset in assets {
            imageManager.requestImage(for: asset, targetSize: size, contentMode: .aspectFill, options: options) { [weak self] image, info in
                guard let image = image else { return }
                self?.images.append(image)
            }
        }


with my regards

Aqeel
