### ISSUE TITLE
TitleLabel and SubtitleLabel doesn't show properly

### ISSUE THREAD

**Issue by tnylee** [tilltue/TLPhotoPicker#182]
```
configure.defaultCameraRollTitle = "Camera Roll".localized()
configure.tapHereToChange = "Tap here to change".localized()
```

How it looked on my devices running iOS 11.4 and 12.2

<img width="540" alt="Screen Shot 2562-05-14 at 14 13 27" src="https://user-images.githubusercontent.com/7221867/57678243-fd440500-7652-11e9-955b-e26f57398cdd.png">

**Comment by tilltue** [comment]
@tnylee 
In my case, it works. 
<img width="455" alt="스크린샷 2019-05-18 오전 1 05 10" src="https://user-images.githubusercontent.com/2108446/57941131-0e1da080-7909-11e9-8885-47ebd3c2eaf7.png">
