### ISSUE TITLE
Filter out GIF 

### ISSUE THREAD

**Issue by omerCoosto** [tilltue/TLPhotoPicker#183]
based on #123 and @tilltue [reply](https://github.com/tilltue/TLPhotoPicker/pull/123#issuecomment-397631260), I was trying to filter the GIF type media as i don't want to show them to the users. 

I use the following code for that: 

```
        var config = TLPhotosPickerConfigure()
        let options = config.fetchOption ?? PHFetchOptions()

        options.sortDescriptors = [NSSortDescriptor(key: "creationDate", ascending: false)]

        if #available(iOS 11.0, *) {
            options.predicate = NSPredicate(format: "playbackStyle != %d", PHAsset.PlaybackStyle.imageAnimated.rawValue)
        } else {
//        options.predicate = NSPredicate(format: "uniformTypeIdentifier == %@", kUTTypeGIF as String)
        }
        config.fetchOption = options
```

Unfortunately for lower than iOS 11 i cannot find the solution to filter out GIF medias as i cannot use **NSPredicate(block:)** and via **NSPredicate(format:)** i cannot fetch the value for key "**uniformTypeIdentifier**".

Is there anyone who has a solution for that?

PS: **NSPredicate(block:)**, can't be used because the library append other String format predicate after the block predicate which mess up the block predicate

**Comment by tilltue** [comment]
@omerCoosto 
As I know it, can't filter the gif file.
https://github.com/tilltue/TLPhotoPicker/issues/145
