### ISSUE TITLE
iOS 13 crash

### ISSUE THREAD

**Issue by MrFuFuFu** [tilltue/TLPhotoPicker#187]
Hi there again, 

thanks for the great library.

Here is the error video I got from users. Some of users already upgrade to iOS 13 beta version and they crash when they open the selecting photo page.

I haven't update my iPhone to iOS 13 yet. Will try to upgrade to iOS 13 as soon as possible to see what's the error is.

![ezgif-1-a648b939d419](https://user-images.githubusercontent.com/6850766/60148229-5db68c80-9824-11e9-90ee-f6b2e023b2e6.gif)

**Comment by MrFuFuFu** [comment]
![image](https://user-images.githubusercontent.com/6850766/60174385-04bb1880-9865-11e9-85e2-b49ba056640a.png)

**Comment by MrFuFuFu** [comment]
Hi just turn `autoPlay` off and the problem solved. So it's the playVideo bug I assume

**Comment by tilltue** [comment]
@MrFuFuFu 
Actually, i am not update to my iPhone iOS13 yet. 😢

**Comment by JakeAtSportsYou** [comment]
Hi,
This issue happens not only iOS 13 but also in iOS 12. I've noticed the problem in the code. 

There are a couple of places that dispatch video playing command in a **synchronous** way using "DispatchQueue.main.SYNC" even though the place is the main thread. If we change "DispatchQueue.main.sync" to "**DispatchQueue.main.async**", the problem will be resolved.

**Comment by tilltue** [comment]
@MrFuFuFu
I've push that and released 1.9.0
Thanks. @JakeAtSportsYou 👍

**Comment by MrFuFuFu** [comment]
Problem solved. thanks a lot.
