### ISSUE TITLE
Single Selection - previous selection stays visible

### ISSUE THREAD

**Issue by KKranjcevic** [tilltue/TLPhotoPicker#188]
If you select one image and scroll it out of bounds just a little, select another image and scrolling back, the previous selection is visible. If you scroll more out of bounds the previous selection disappears.
![tlPhotoSingleSelectionBug](https://user-images.githubusercontent.com/31131605/60573265-9ea82700-9d77-11e9-8a64-6f065eb35a2b.gif)

**Comment by tilltue** [comment]
@KKranjcevic 
Thank you for letting me know.
I think it should work now. I've pushed a fix for this. ( in release 1.9.1 )

**Comment by KKranjcevic** [comment]
Now it won't deselect if you are not scrolling so I get multi no 1 selected cells. If you scroll forward and back the selected ones are removed.

**Comment by KKranjcevic** [comment]
I have been playing around and on 1.9.0 build in willDisplayCell delegate function I just removed in if statement self.usedPrefetch. The main problem in this particular case is that cellForItemAt is not called but willDisplayCell is (for items just little out of bounds) and cell.selectedAsset is not set again because of self.usedPrefetch.

**Comment by tilltue** [comment]
@KKranjcevic 
OMG 😂
I am sorry. I slipped up.

**Comment by tilltue** [comment]
@KKranjcevic 
Sorry again. I thought it was modified but there was still a bug. 
[release 1.9.3](https://github.com/tilltue/TLPhotoPicker/commit/bdb091f59aed6ad94b7bd7f64eb9f996f27f2825)
