### ISSUE TITLE
Dear Author,

### ISSUE THREAD

**Issue by brandy2015** [tilltue/TLPhotoPicker#189]
![IMG_8176](https://user-images.githubusercontent.com/10484324/61342020-4e52be00-a87b-11e9-8cd8-ddd6a953e4c0.PNG)
I find one little bug .

configure.singleSelectedMode = true

Then you pick one photo and another one .  It happens to flash out . When you restart it, you will find it can select many pictures at the same time.

**Comment by brandy2015** [comment]
Especially, it happened at GIF selection mode.

**Comment by tilltue** [comment]
@brandy2015 
Thank you so much.
I modified it before, but there was still a bug.
https://github.com/tilltue/TLPhotoPicker/issues/188
Fixed 1.9.3
[release 1.9.3](https://github.com/tilltue/TLPhotoPicker/commit/bdb091f59aed6ad94b7bd7f64eb9f996f27f2825)
