### ISSUE TITLE
Can you add 'pushToViewController' delegate method after select images?

### ISSUE THREAD

**Issue by ramboli1986** [tilltue/TLPhotoPicker#19]
Hi tilltue, 

First, thank you for your awewome work!
Actual this is not a issue. All I need is push to my customer view controller after tap done button of photo picker, but now we can dismiss the picker only. Could you please add a delegate method to implement push to my custom View Controller with PHAsset array? Thanks.

**Comment by tilltue** [comment]
hi @ramboli1986 
It may be more complicated to interact custom viewcontroller.
( navigation back transition, dismiss viewcontroller, etc. )
I think it will take a few days. 
but i'll try.

**Comment by ramboli1986** [comment]
Thank you so much. Appreciate for your awesome job!

**Comment by tilltue** [comment]
hi @ramboli1986 
i added an example.
e5fee75517abf4a42752e4f48077edc834371b95
