### ISSUE TITLE
Dear Author, orientation detection?

### ISSUE THREAD

**Issue by brandy2015** [tilltue/TLPhotoPicker#191]
How can I configure the orientation when I present the TLPhotoPicker?

**Comment by brandy2015** [comment]
I got it. 

var configure = TLPhotosPickerConfigure()
        configure.supportedInterfaceOrientations = [.landscape,.landscapeLeft,.landscapeRight]

**Comment by brandy2015** [comment]
I recommend that 

TLPhotosPickerConfigure {
。。。
public var supportedInterfaceOrientations: UIInterfaceOrientationMask = [.all]
}

[.portrait]  to [.all]

**Comment by tilltue** [comment]
@brandy2015 

That can be easy way, but it must consider collectionview flowlayout if landscape mode. my guess is it would much complexity. 
In better way, Used custom TLPhotopicker ViewController that supported landscape mode and used custom flowlayout.

**Comment by brandy2015** [comment]
When I use this kit on iPad, it wil throw a weird problem.
