### ISSUE TITLE
Build fail Xcode 10.3

### ISSUE THREAD

**Issue by shial4** [tilltue/TLPhotoPicker#192]
Pods/TLPhotoPicker/TLPhotoPicker/Classes/TLPhotoCollectionViewCell.xib:-1: Failed to find or create execution context for description '<IBCocoaTouchPlatformToolDescription: 0x7fbba49ab7b0> System content for IBCocoaTouchFramework-NineOneAndLater <IBScaleFactorDeviceTypeDescription: 0x7fbba497f2f0> scaleFactor=2x'. These intermediate objects were non-nil: (

**Comment by logicsb** [comment]
sudo killall -9 com.apple.CoreSimulator.CoreSimulatorService

will sove this issu
