### ISSUE TITLE
How to disable camera cell?

### ISSUE THREAD

**Issue by jemzubiri** [tilltue/TLPhotoPicker#193]
Can't seem to disable the camera cell in the selection

**Comment by tilltue** [comment]
Hi,  @jemzubiri 
TLPhotosPickerConfigure
configure.usedCameraButton = false

**Comment by jemzubiri** [comment]
![image](https://user-images.githubusercontent.com/21273687/61803951-a5512800-ae65-11e9-9578-62bc36c4c53a.png)
![image](https://user-images.githubusercontent.com/21273687/61803974-b0a45380-ae65-11e9-9348-42325a8070f0.png)

**Comment by tilltue** [comment]
@jemzubiri 

        let viewController = TLPhotosPickerViewController()
        var configure = TLPhotosPickerConfigure()
        configure.usedCameraButton = false
        **viewController.configure = configure**

**Comment by jemzubiri** [comment]
Completely missed that. Thank you so much!
