### ISSUE TITLE
Options to disable smart album selection?

### ISSUE THREAD

**Issue by shivanraptor** [tilltue/TLPhotoPicker#194]
I would like to allow my users to select videos in the Videos folder only. Is it possible to have an option / config to disable smart album selection and defaults to Videos folder only?

**Comment by tilltue** [comment]
Hi, @shivanraptor 
Yes you can. 
```swift3
configure.fetchCollectionTypes = [(PHAssetCollectionType.album, PHAssetCollectionSubtype.smartAlbumVideos)]
```

**Comment by shivanraptor** [comment]
Great. I can now select only videos using the codes below:

        let vc = TLPhotosPickerViewController()
        vc.delegate = self
        var config = TLPhotosPickerConfigure()
        config.fetchCollectionTypes = [(PHAssetCollectionType.smartAlbum, PHAssetCollectionSubtype.smartAlbumVideos)]
        config.singleSelectedMode = true
        vc.configure = config
        self.present(vc, animated: true, completion: nil)

However, how can I obtain the video local URL in the delegate function `func dismissPhotoPicker(withTLPHAssets: [TLPHAsset])`? Seems `TLPHAsset` class does not provide an `URL` property. Thanks.

**Comment by shivanraptor** [comment]
Solved the problem. Using the answer [here](https://stackoverflow.com/a/44630089/188331), and access the URL via `phAsset` property.
