### ISSUE TITLE
iOS13 – Cannot disable camera button

### ISSUE THREAD

**Issue by TerenzeY** [tilltue/TLPhotoPicker#196]
In iOS13 Beta 5, the property "usedCameraButton" seems to have no effect anymore?

Also if we allow it, after taking photo using the camera cell the photos cells do not get updated.

**Comment by tilltue** [comment]
Actually, i am not update to my iPhone iOS13 yet. 😢

**Comment by nvish-sanjeevthapar** [comment]
I am facing same issue in iOS 12. Did you guys find any fix for it.

**Comment by tilltue** [comment]
@nvish-sanjeevthapar 
It's working normally on the samples. 
Can you show me the setup configuration code? ( TLPhotosPickerConfigure )

**Comment by Vincent-Loi** [comment]
Below is my configuration setup, not sure if anything else will affect it but I have set `usedCameraButton` to `false` already - works on iOS 12 though.

```
var configure = TLPhotosPickerConfigure()
configure.numberOfColumn = 4
configure.autoPlay = false
configure.usedPrefetch = true
configure.usedCameraButton = false
configure.allowedVideo = false
configure.allowedVideoRecording = false
configure.maxSelectedAssets = 10
configure.cancelTitle = "Cancel"
configure.doneTitle = "Done"
```
