### ISSUE TITLE
Make pop view animation duration customizable?

### ISSUE THREAD

**Issue by danqing** [tilltue/TLPhotoPicker#198]
Great library - thank you! I'm wondering if the animation duration of the pop view can be made a config. 0.1s seems really short and it'd be great if it's customizable.

https://github.com/tilltue/TLPhotoPicker/blob/bdb091f59aed6ad94b7bd7f64eb9f996f27f2825/TLPhotoPicker/Classes/TLAlbumPopView.swift#L32

Speaking of which, there's a white (light gray?) divider line in black mode. Maybe it can be changed to some darker shade?

<img width="403" alt="Screen Shot 2019-08-09 at 4 47 47 PM" src="https://user-images.githubusercontent.com/5134133/62766616-71147300-bac5-11e9-9839-a7e72ce599b6.png">

**Comment by tilltue** [comment]
Hi, @danqing 
I added configure for popup. ( version 1.9.4 )
```swift3
        var configure = TLPhotosPickerConfigure()
        configure.popup = [PopupConfigure.animation(3)]
        //...
```

for Example 
CustomBlackStylePickerViewController.swift 

```swift3
class CustomBlackStylePickerViewController: TLPhotosPickerViewController {
    override func makeUI() {
        super.makeUI()
        //...
        self.albumPopView.tableView.separatorColor = (your color) // 👈
    }
```

**Comment by danqing** [comment]
That's great to know - appreciate the quick turnaround!

For the separator, do you think it makes sense to default the black style color to some darker shade? (great to be able to customize it for sure)
