### ISSUE TITLE
Cancelling Image Picker submits change on the Image Picker instance

### ISSUE THREAD

**Issue by datureezy** [tilltue/TLPhotoPicker#2]
Select 3 photos, press Done.

Open Image Picker again, deselect 1 photo, and Cancel.

Open Image Picker again, it should be 3 photos, but it has changed to 2

---

Same with the opposite scenario.

Open Image Picker, select 3 photos, and Cancel.

Open Image Picker again, there are 3 photos already selected.

///

Just wanted to point this case out to you. This is only in the case where the view controller presenting the image picker is holding a reference to the image picker. You show your code instantiating a new image picker each time so this wouldn't happen in your example code.

You can close this issue if you intended to never instantiate and hold a reference within the calling view controller.

**Comment by tilltue** [comment]
you can use this. 😄 
```swift
class ViewController: UIViewController,TLPhotosPickerViewControllerDelegate {
    let viewController = TLPhotosPickerViewController()
    var selectedAssets = [TLPHAsset]()
    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.\
        self.viewController.delegate = self
        var configure = TLPhotosPickerConfigure()
        configure.numberOfColumn = 3
        self.viewController.configure = configure
    }
        
    @IBAction func pickerButtonTap() {
        **self.viewController.selectedAssets = self.selectedAssets**
        self.present(viewController, animated: true, completion: nil)
    }
    func dismissPhotoPicker(withTLPHAssets: [TLPHAsset]) {
        // use selected order, fullresolution image
        self.selectedAssets = withTLPHAssets
    }
}
```
