### ISSUE TITLE
Allow exporting non-MOV

### ISSUE THREAD

**Issue by danqing** [tilltue/TLPhotoPicker#200]
I understand that there's #184. Looking through the code, I think it is a good idea to allow exporting other types of video files here:

https://github.com/tilltue/TLPhotoPicker/blob/4863c7be2bd6c13ecd53c2795d5de4e5a15ab092/TLPhotoPicker/Classes/TLAssetsCollection.swift#L251

Also, in #42 you mentioned `tempCopyMediaFile`. Does `exportVideoFile` handle iCloud too? I see `networkAllowed` in there, but the iCloud part is commented out. Would love to have some clarity here.

Thank you!

**Comment by tilltue** [comment]
Hi, @danqing
There were some bugs in the function, so I modified it. ( release 1.9.5 )
You can now use it and download the iCloud video.
Thank you.

**Comment by danqing** [comment]
Cool - thanks @tilltue! Would love to have support for exporting formats other than mov, which I believe should be pretty simple (changing the line I referenced above with some config).

**Comment by tilltue** [comment]
@danqing 
added outputFileType
```swift3
func exportVideoFile(options: PHVideoRequestOptions? = nil,
                                outputURL: URL? = nil,
                                outputFileType: AVFileType = .mov,
                                progressBlock:((Double) -> Void)? = nil,
                                completionBlock:@escaping ((URL,String) -> Void))
```

**Comment by danqing** [comment]
Awesome. Thanks again @tillhue!
