### ISSUE TITLE
Album sort order

### ISSUE THREAD

**Issue by Johnson145** [tilltue/TLPhotoPicker#201]
May I ask whether the list of albums (not the photo list within an album) is sorted in a particular way?

It's not sorted alphabetically. Nor does it pay attention to the manual order which can be specified by the user from within the native Photos app.

**Comment by tilltue** [comment]
```swift3
public struct TLPhotosPickerConfigure {
//...
public var fetchCollectionTypes: [(PHAssetCollectionType,PHAssetCollectionSubtype)]? = nil
//...
```
Please, try use this configure options.

**Comment by Johnson145** [comment]
Thanks for your quick help!

I want to keep the same albums as are give by default. I just want to change their order. Please correct me, if I'm wrong, but the option you've mentioned would require me to duplicate [the relevant default code](https://github.com/tilltue/TLPhotoPicker/blob/a42179b909ab3283ae2275092e76b99eeb8a814f/TLPhotoPicker/Classes/TLPhotoLibrary.swift#L199-L253), right? Wouldn't it be a better option to provide a way to sort the albums you provide?

In general, I'm okay with the order of the smart albums. Only the order of the "usual albums" confused some users. So I guess all we need would be the `with` parameter of the [PHCollectionList.fetchTopLevelUserCollections(with: nil)](https://github.com/tilltue/TLPhotoPicker/blob/a42179b909ab3283ae2275092e76b99eeb8a814f/TLPhotoPicker/Classes/TLPhotoLibrary.swift#L240). It natively supports providing a [sortDescriptor](https://developer.apple.com/documentation/photokit/phfetchoptions/1624771-sortdescriptors). The documentation states that you're currently using the default options, but I couldn't find the actual default value yet. Don't you think that it would make sense to explicitly set the album order in your code to e.g. an alphabetical one?

**Comment by tilltue** [comment]
@Johnson145 
I added fetchCollectionOption. (release 1.9.7)
:)

**Comment by Johnson145** [comment]
Thank you very much for the update! It's working like a charm :)

In case anybody else needs a full example, this is how I sort the albums alphabetically:
```Swift
var configure = TLPhotosPickerConfigure()
let fetchOptions = PHFetchOptions()
fetchOptions.sortDescriptors = [NSSortDescriptor(key: "localizedTitle", ascending: true)]
configure.fetchCollectionOption[.assetCollections(.smartAlbum)] = fetchOptions
configure.fetchCollectionOption[.assetCollections(.album)] = fetchOptions
configure.fetchCollectionOption[.topLevelUserCollections] = fetchOptions
imagePickerController.configure = configure
```
