### ISSUE TITLE
exportVideoFile: need a custom export path

### ISSUE THREAD

**Issue by iOSSer** [tilltue/TLPhotoPicker#203]
like this:
`public func exportVideoFile(options: PHVideoRequestOptions? = nil,pathHeader:String? = nil, progressBlock:((Float) -> Void)? = nil, completionBlock:@escaping ((URL,String) -> Void))`

`        guard let phAsset = self.phAsset, phAsset.mediaType == .video else { return }
        var type = PHAssetResourceType.video
        guard let resource = (PHAssetResource.assetResources(for: phAsset).filter{ $0.type == type }).first else { return }
        let fileName = "_Video***" + resource.originalFilename
        var writeURL: URL? = nil
        if #available(iOS 10.0, *) {
            //            writeURL = FileManager.default.temporaryDirectory.appendingPathComponent("\(fileName)")
            writeURL = URL.init(fileURLWithPath: pathHeader!).appendingPathComponent("\(fileName)")
        } else {
            //            writeURL = URL(fileURLWithPath: NSTemporaryDirectory(), isDirectory: true).appendingPathComponent("\(fileName)")
            writeURL = URL.init(fileURLWithPath: pathHeader!, isDirectory: true).appendingPathComponent("\(fileName)")
        }`

**Comment by tilltue** [comment]
Hi @iOSSer 
```swift3
func exportVideoFile(options: PHVideoRequestOptions? = nil,
                                outputURL: URL? = nil,
                                outputFileType: AVFileType = .mov,
                                progressBlock:((Double) -> Void)? = nil,
                                completionBlock:@escaping ((URL,String) -> Void))
```
added outputURL :)
