### ISSUE TITLE
Duration view on custom cell

### ISSUE THREAD

**Issue by EgorVeremeychikEffectiveSoft** [tilltue/TLPhotoPicker#206]
I set `allowedVideo` to false.
Probably you should set `cell?.durationView?.isHidden` to false value by default.

I understand, that I can handle it in my custom cell, but it will be better do it in `TLPhotoCollectionViewCell`

**Comment by tilltue** [comment]
Hi, @EgorVeremeychikEffectiveSoft 
The option is not to allow video selection. That's why it's hidden.

allowedVideo == false
not want show video type assets -> durationView.isHidden = true

**Comment by EgorVeremeychikEffectiveSoft** [comment]
@tilltue Yes, right!
But in my custom cell `durationView.isHidden = true` by default. 
I set `allowedVideo` to  false, but I still see durationView with durationLabel
