### ISSUE TITLE
please help!

### ISSUE THREAD

**Issue by hell4opt** [tilltue/TLPhotoPicker#207]
re-saved the photos in the album as new, but they remain in the same places when choosing, but not at the end (as in the story on Instagram this is terrible, how can I fix it?

**Comment by tilltue** [comment]
Hi, @hell4opt 
Can you show me the screenshot when there's problem?

**Comment by hell4opt** [comment]
hi! video: https://yadi.sk/i/b-r77LjbJ-eFWw

**Comment by tilltue** [comment]
@hell4opt 

This is because the sort option is based on the date it was created.
Look at this document and choose the PHFetchOptions you want.
https://developer.apple.com/documentation/photokit/phfetchoptions
```swift3
let viewController = TLPhotosPickerViewController()
var configure = TLPhotosPickerConfigure()
configure.fetchOption = //<- and set here
viewController.configure = configure
```
