### ISSUE TITLE
defaultCameraRollTitle

### ISSUE THREAD

**Issue by LQYaphets** [tilltue/TLPhotoPicker#208]
defaultCameraRollTitle field invalid

**Comment by tilltue** [comment]
Hi, @LQYaphets 
```swift3
public struct TLPhotosPickerConfigure {
    public var customLoclizedTitle: [String: String] = ["Camera Roll": "Camera Roll"] // Set [:] if you want use default localized title of album 
...
}
```
Added customization for localized title of album. 07f7a0c8e539ed1492915edf8639d5eb8ae6c6c2
It going to be included in release 1.9.8.

**Comment by LQYaphets** [comment]
I used it in the project, modified part of the source code, it works well,helped me a lot.

**Comment by tilltue** [comment]
I've pushed a fix for this. release 1.9.8
