### ISSUE TITLE
Can not display images

### ISSUE THREAD

**Issue by liushuangddu** [tilltue/TLPhotoPicker#21]
When I use the TLPhotosPickerViewController  or custom controller ,they all can not display any images ,Only I deleted the app and reinstall could be display once ,after dismiss the controller ,re presnet the pickerViewcontroller could not display amy images.

I dont know what it is the problem , but your demo could run normally .

**Comment by tilltue** [comment]
hi @liushuangddu 
it happen to any device and any simulator?

**Comment by liushuangddu** [comment]
yes .I have test on my phone and my friends phone ,not display either.And we running iOS 10.3.2.
iPhone 6 and iPhone 6s

**Comment by tilltue** [comment]
i'm sorry. it was impossible to reproduce. at any device.
