### ISSUE TITLE
Can not fetch images from AirDrop

### ISSUE THREAD

**Issue by KittenYang** [tilltue/TLPhotoPicker#210]
If you AirDrop a picture from mac to iPhone, this framework can not fetch it.

**Comment by tilltue** [comment]
Hi, @KittenYang 
When I tested it, it was normal.
Did I miss anything?
![무제](https://user-images.githubusercontent.com/2108446/64075344-17811c00-ccf2-11e9-8fd0-4bb6feb62543.gif)

**Comment by KittenYang** [comment]
Hi,@tilltue, I found that it's maybe my phone's bug. Too weird. I've tested AirDrop a photo from Mac to iPhone, but it seems only appearing in Albums Page(Tab 3) not in Photos Page(Tab 1).No idea😥. But your code is OK, sorry, my fault.
![IMG_6715 TRIM 2019-09-02 01_48_59](https://user-images.githubusercontent.com/5517281/64080189-e4f01700-cd23-11e9-811f-43dc7f35a168.gif)
