### ISSUE TITLE
PickerView orientation change

### ISSUE THREAD

**Issue by arne-walters** [tilltue/TLPhotoPicker#211]
Opening the PhotoPicker in Portrait and clicking on the pickerView works just fine.
However if you close the pickerView, rotate the device and click on the pickerView again the frame of the pickerView will be just the same as the one in Portrait mode.

correct frame in portrait mode
<img width="636" alt="Bildschirmfoto 2019-08-30 um 11 45 23" src="https://user-images.githubusercontent.com/54707020/64011424-f4047880-cb1b-11e9-9535-8148591b55b3.png">

wrong frame after opening it again in landscape
<img width="865" alt="Bildschirmfoto 2019-08-30 um 11 45 37" src="https://user-images.githubusercontent.com/54707020/64011438-f961c300-cb1b-11e9-9958-96663953c80c.png">

**Comment by tilltue** [comment]
Hi, @arne-walters 
Sorry, you need to customization more detail for support orientation.
Related issue https://github.com/tilltue/TLPhotoPicker/issues/191
