### ISSUE TITLE
method photoSize for livePhotos

### ISSUE THREAD

**Issue by kmatskevich** [tilltue/TLPhotoPicker#212]
Hi guys, 

Firstly: thanks for this library! 

I found a bug and don't want to create a new pull request for it. The main problem is: if you'll try to check the size of the livephoto - the func will return -1.

The wrong place is in the file TLAssetsCollection.swift
func photoSize(options: PHImageRequestOptions? = nil ,completion: @escaping ((Int)->Void), livePhotoVideoSize: Bool = false)
line 74: guard let phAsset = self.phAsset, self.type == .photo else { completion(-1); return }

fixed line: guard let phAsset = self.phAsset, self.type == .photo || self.type == .livePhoto else { completion(-1); return }

Please, add it to the library.
Thanks in advance!

**Comment by tilltue** [comment]
Looks good! Thanks, @kmatskevich
