### ISSUE TITLE
Custom localized title works only when it shows for the first time

### ISSUE THREAD

**Issue by heesun0064** [tilltue/TLPhotoPicker#216]
I tried the custom localized title but it shows the localized title only when it shows the first time.
If I click "tap here to change" and select other type such as selfies, panoramas then it shows the English title not localized title.

ex) configure.customLoclizedTitle = ["Camera Roll": "카메라 롤", "All Photos":"전체", "Selfies": "셀카", "Panoramas": "파노라마"]

**Comment by tilltue** [comment]
I think it should work release 2.0.0 I've pushed a fix for this.
