### ISSUE TITLE
Getting Video File

### ISSUE THREAD

**Issue by rtemple6** [tilltue/TLPhotoPicker#22]
Could you help me get the URL for when they select a video file.

I am trying to upload the selected video to my backend (Firebase), and currently I can't seem to figure out how to get the file URL for the selected video.

Is there something similar to 
public var fullResolutionImage: UIImage? {
        get {
            guard let phAsset = self.phAsset else { return nil }
            return TLPhotoLibrary.fullResolutionImageData(asset: phAsset)
        }
    }

That can be accessed within dismissPhotoPicker(withTLPHAssets:) so I can get the URL for the video I selected?  Or am I going about this the wrong way.

**Comment by tilltue** [comment]
hi @rtemple6 
used this code. :)
if you want upload video asset, you have to copy temporary file. ( don't forget remove file after uploaded )

extension PHAsset {
    func tempCopyMediaFile() -> (url: URL,mimetype: String)? {
        if self.mediaType != .video { return nil }
        guard let resource = PHAssetResource.assetResources(for: self).first else { return nil }
        let fileName = resource.originalFilename
        var writeURL: URL? = nil
        if #available(iOS 10.0, *) {
            writeURL = FileManager.default.temporaryDirectory.appendingPathComponent("\(fileName)")
        } else {
            writeURL = URL(fileURLWithPath: NSTemporaryDirectory(), isDirectory: true).appendingPathComponent("\(fileName)")
        }
        guard let localURL = writeURL,let mimetype = fileName.MIMEType() else { return nil }
        let options = PHAssetResourceRequestOptions()
        options.isNetworkAccessAllowed = false
        var ret: (url: URL,mimetype: String)? = nil
        PHAssetResourceManager.default().writeData(for: resource, toFile: localURL, options: options, completionHandler: { error in
            if let error = error {
                print(error.localizedDescription)
            }
            ret = (localURL,mimetype)
        })
        return ret
    }
    func videoSize(completion: @escaping ((Int)->Void)) {
        PHImageManager.default().requestAVAsset(forVideo: self, options: nil) { (avasset, audioMix, info) in
            var url: URL? = nil
            if let urlAsset = avasset as? AVURLAsset {
                url = urlAsset.url
            }else if let sandboxKeys = info?["PHImageFileSandboxExtensionTokenKey"] as? String, let path = sandboxKeys.components(separatedBy: ";").last {
                url = URL(fileURLWithPath: path)
            }
            completion(url?.fileSize() ?? -1)
        }
    }
}

**Comment by rtemple6** [comment]
Thank you! You saved me from hours of frustration trying to figure that out!

**Comment by ErAshu** [comment]
Hi @tilltue 
I am using this lib and i have to copy video in document directory. i am using this code but getting error in this line:
`guard let localURL = writeURL,let mimetype = fileName.MIMEType() else { return nil }`

it says that

`value of type 'String' has no member 'MIMEType'`

and in the last line here:
`completion(url?.fileSize() ?? -1)`
it says:

`value of type 'URL' has no member 'fileSize'`

Please fix these for **Swift 4.0**

**Comment by tilltue** [comment]
@ErAshu
Use this. 
https://github.com/tilltue/TLPhotoPicker/blob/master/TLPhotoPicker/Classes/TLAssetsCollection.swift
```swift
//line 123 
func MIMEType(_ url: URL?) -> String? {
...
}

//line 140
public func tempCopyMediaFile(progressBlock:((Double) -> Void)? = nil, completionBlock:@escaping ((URL,String) -> Void)) -> PHImageRequestID? {
...
}
```

**Comment by ErAshu** [comment]
Thanks @tilltue
