### ISSUE TITLE
Image Sorting

### ISSUE THREAD

**Issue by bport95** [tilltue/TLPhotoPicker#220]
I am trying to get the images to sort with newest images on bottom and oldest images on top(similar to the iOS Photos app). Per Issue 71, I tried adding this block of code to the TLPhotosPickerConfigure instance of my picker:
```
  let options = PHFetchOptions()
  let sortOrder = [NSSortDescriptor(key: "creationDate", ascending: true)]
  options.sortDescriptors = sortOrder
  configure.fetchOption = options
```

The ordering does not seem to change, even if I change ascending to `false`. I was looking into the `TLPhotoLibrary` and it looks like the `sortDescriptors` property is being modified in the `getOption` function of `TLPhotoLibrary.swift` to have a value of `false`, regardless of the value that is passed in to the `TLPhotosPickerConfigure` object.

**Comment by tilltue** [comment]
@bport95 
It should work release 2.0.1 But i can't published Because cocoapods bugs.
