### ISSUE TITLE
Selecting multiple live images crashes Example app

### ISSUE THREAD

**Issue by jtressle** [tilltue/TLPhotoPicker#221]
Hi,

Great library.  I believe there's a memory leak when selecting live images.  You can replicate the issue by:

- Running your example
- Selecting 'Show Picker'
- Selecting about 20-30 live images.  

The app will crash with a memory error.  Is this an issue with how the PHAsset is handled on Apple's end?  I just took these images so prefetching shouldn't be an issue.  

Thanks!

**Comment by tilltue** [comment]
@jtressle 
Thanks you. Let me check this. :)

**Comment by tilltue** [comment]
@jtressle 
I think it is work release 2.0.4. I've fixed that and push now.

**Comment by jtressle** [comment]
@tilltue awesome!  It works with 45 images.  Thanks a bunch!
