### ISSUE TITLE
Hey,dear friend,long time no see.

### ISSUE THREAD

**Issue by brandy2015** [tilltue/TLPhotoPicker#222]
How can I disable the done button on the right ,when I selected no pic? In the other words, how can I secure the done button when choose no pic. Thanks.😬

**Comment by tilltue** [comment]
Hi @brandy2015 :)
I changed to access control levels of 'selectedAssets' property.

```swift3
class CustomPhotoPickerViewController: TLPhotosPickerViewController {
    
    override var selectedAssets: [TLPHAsset] {
        willSet {
            self.doneButton?.isEnabled = newValue.count > 0
        }
    }
//...
```

**Comment by brandy2015** [comment]
Thanks😬

**Comment by brandy2015** [comment]
Overriding non-open property outside of its defining module

**Comment by brandy2015** [comment]
![屏幕快照 2019-09-30 下午10 17 37](https://user-images.githubusercontent.com/10484324/65887194-1fef7400-e3d0-11e9-8f2b-77b16deb490f.png)
I overrided it but then I got this error.

**Comment by tilltue** [comment]
@brandy2015 
My Guess is you need to update library.

**Comment by brandy2015** [comment]
Got it.
