### ISSUE TITLE
Support Swift Package Manager?

### ISSUE THREAD

**Issue by danqing** [tilltue/TLPhotoPicker#224]
Now that Xcode 11 supports SPM natively, it would be great if this awesome library can adopt SPM as well. Thank you!

**Comment by tilltue** [comment]
Hi, @danqing 
Actually, I tried support Swift Package Manager, but there is can not include bundle resources. 😢( not yet )
Related issue : https://bugs.swift.org/browse/SR-2866

**Comment by danqing** [comment]
Ah I see. Hope it will be supported soon!
