### ISSUE TITLE
Objective-C Import

### ISSUE THREAD

**Issue by Offek** [tilltue/TLPhotoPicker#225]
Hello all,
thanks for this great library.
I'm having trouble using the library with objective c.
I've added the objective-c branch to the Podfile as follows:
`pod "TLPhotoPicker", :git =>
  'https://github.com/tilltue/TLPhotoPicker.git', :branch => 'objective-c'`

I tried importing the library using:
`@import TLPhotoPicker;`
and
`#import "TLPhotoPicker-Swift.h"`

However either way I can only access `TLPhotosPickerViewController`; delegates and other classes do not seem accessible. I definitely can't run the objective-c sample code specified in the README. Am I doing something wrong?

Thanks

**Comment by tilltue** [comment]
Hi, @Offek 
Some class (e.g. TLPhotosPickerViewController) have open access control level.
Please can you explain what you want to access other class property or something?

**Comment by Offek** [comment]
Hi, @tilltue 
I'm trying to run the example in the README, but nothing works everything seems to be undefined.
I can only manage to open TLPhotosPickerViewController, but I can't do anything with it as the delegate is "undefined" and therefore unusable. Therefore I can't seem to do anything in Objective C code. I was wondering if anyone else is also experiencing these issues.

**Comment by rizwan95** [comment]
> Hi, @tilltue
> I'm trying to run the example in the README, but nothing works everything seems to be undefined.
> I can only manage to open TLPhotosPickerViewController, but I can't do anything with it as the delegate is "undefined" and therefore unusable. Therefore I can't seem to do anything in Objective C code. I was wondering if anyone else is also experiencing these issues.

What is the exact problem are you facing? I am using that branch in my objective-c project and it works.

**Comment by Offek** [comment]
Hello @rizwan95, thanks for your time.
Do you use Cocoapods to import the project, or did you copy the project locally? How do you import it? Using the TLPhotoPicker-Swift.h file?

When I download the project using cocoapods (objc branch) and import using TLPhotoPicker-Swift.h (or @import), I’m only able to open TLPhotosPickerViewController, but it doesn’t call the delegate. Xcode says the delegate is undefined. The sample code in the readme is not working due to the same issue, everything is undefined except TLPhotosPickerViewController.

**Comment by rizwan95** [comment]
As of now, can you please drag and drop the files?

**Comment by Offek** [comment]
Hi, 
I found out how to use it correctly.
It would be nice if you could update the Objective-C documentation to hopefully help more people in the future and prevent confusion. This is how I got it to work with Cocoapods:
`pod "TLPhotoPicker", :git => 'https://github.com/tilltue/TLPhotoPicker.git', :branch => 'objective-c'`

```
#import "TLPhotoPicker-Swift.h"


TLPhotosPickerViewController *picker = [[TLPhotosPickerViewController alloc] initWithPHAssets:^(NSArray<PHAsset*> *assets) {
        NSLog(@"selected assets: %@", assets);
} didCancel:^{
        NSLog(@"Picker Cancelled");}];
[self presentViewController:picker animated:YES completion:nil];
```

**Comment by rizwan95** [comment]
Yes, as you said the documentation needs to be updated. We have only little information about objective-c usage. 

https://github.com/tilltue/TLPhotoPicker/tree/objective-c
