### ISSUE TITLE
After updating iOS 13.1 and Xcode 11.0 on asset.exportVideoFile not getting Video URL

### ISSUE THREAD

**Issue by khotbhagya13** [tilltue/TLPhotoPicker#227]

**Comment by tilltue** [comment]
@khotbhagya13 
<img width="881" alt="스크린샷 2019-11-09 오후 2 55 28" src="https://user-images.githubusercontent.com/2108446/68523766-fc89e400-0300-11ea-8b17-6b32a7eaa1db.png">
I can't reproduce that.
(using example app, iPhoneX)
