### ISSUE TITLE
Support semantic versioning

### ISSUE THREAD

**Issue by danqing** [tilltue/TLPhotoPicker#228]
I come to realize that this library doesn't really follow semantic versioning. For example it goes from 1.9.9 to 2.0.0 (and 1.8.9 to 1.9.0, etc). Can semantic versioning be adopted? That is, make the versioning major.minor.patch.

One particular reason is most dependency managers auto-upgrade within a minor version only, and in general it's a good idea to follow it so people don't need to wonder what's that breaking change 2.0.0 brings about.

**Comment by tilltue** [comment]
Hi, @danqing 
Thank you for your advice. I will consider it and be adopted next release.
