### ISSUE TITLE
Opening any album except camera roll album doesn't affect by photos changes

### ISSUE THREAD

**Issue by menayousif** [tilltue/TLPhotoPicker#231]
I'd like to announce that we depend on your great library on showing and presenting user photos. 

An issue we face that when any album is showing except camera roll album then the user adds or deletes image/images from this opened album; no change affects.

For example I open album named "Mena" and this album contains 3 images when I dismiss the app and go to photos and delete an image from 3 images on "Mena" then back to app; 3 images still present although they should be 2 images. I have to close view controller which contains TLPhotos in order to reload new changes. On the other hand camera roll album is changed in case off user adds/deletes images immediately.

After searching fount that there is a condition guard the photos observer if the current focus collection is not camera roll
```
TLPhotosPickerViewController.swift

extension TLPhotosPickerViewController: PHPhotoLibraryChangeObserver {
    public func photoLibraryDidChange(_ changeInstance: PHChange) {
        guard getfocusedIndex() == 0 else {
            return
        }
.....
```
Your reply is most appreciated

**Comment by tilltue** [comment]
Hi, @menayousif 
photoLibraryDidChange isn't called when users album changes. There is only changes at photos library added new photos or delete photos.

**Comment by menayousif** [comment]
@tilltue 

Thank you for your quick response. 
It is called every time there is a change on photos however the guard condition where is on the top of method's body break in case of the current focused album is not the camera roll album. 
```swift
extension TLPhotosPickerViewController: PHPhotoLibraryChangeObserver {
    public func photoLibraryDidChange(_ changeInstance: PHChange) {
        guard getfocusedIndex() == 0 else {
            return
        }
```
Could you provide?

**Comment by tilltue** [comment]
@menayousif 
remove guard condition lines.
Release 2.0.6

**Comment by menayousif** [comment]
@tilltue 

Thank you so much for your support and help man. 

Well done  :rocket::tada::rocket::tada::rocket::tada:
