### ISSUE TITLE
exportVideoFile: export is very very slow, and can't get the export progress !

### ISSUE THREAD

**Issue by iOSSer** [tilltue/TLPhotoPicker#233]
1. i am export a 35s video need 30 seconds !!!
2.i can't get the export progress, the progressBlock is't return anything !

i hope your fixes this bugs. thanks!

using TLPhotoPicker version 1.8.8, Test Device System: iOS 13

<img width="993" alt="截屏2019-10-2820 58 02" src="https://user-images.githubusercontent.com/3730100/67680290-ec4f3c00-f9c5-11e9-81c1-e99e9d341849.png">

`                let fileName = "_Video***" + asset.originalFileName!;
                print(fileName)
                var writeURL: URL? = nil
                if #available(iOS 10.0, *) {
                    writeURL = URL.init(fileURLWithPath: pathHeader as String).appendingPathComponent("\(fileName)")
                } else {
                    writeURL = URL.init(fileURLWithPath: pathHeader as String, isDirectory: true).appendingPathComponent("\(fileName)")
                }
//                print(writeURL)
                asset.exportVideoFile(options: nil, outputURL: writeURL, outputFileType: .mov, progressBlock: { (progress) in
                    print(progress)
//                    DispatchQueue.main.async {
//                        SVProgressHUD.showProgress(Float(progress))
//                    }

                }) { (assetUrl, mimetype) in
                    let thumnail = self.generateThumnail(url: assetUrl as NSURL).resized(toWidth: coverWidth)
                    try? thumnail!.pngData()?.write(to: URL.init(fileURLWithPath: coverPath), options: Data.WritingOptions.atomic)
                    pcount += 1
                    if withTLPHAssets.count == pcount
                    {
                        DispatchQueue.main.async {
                            SVProgressHUD.dismiss()
//                            self.addButton.isEnabled = true
                            self.reloadAllItems()
                        }
                    }
                }

                break
            case .livePhoto:
                print("livePhoto")
                break
//            default: break
            }`

**Comment by tilltue** [comment]
@iOSSer 
I can't reproduce this, there is immediately exports video.  
(using example app, iPhone X take 33 sec video )
