### ISSUE TITLE
Albums table view data doesn't update after a change in albums

### ISSUE THREAD

**Issue by menayousif** [tilltue/TLPhotoPicker#234]
First of all I would like to thank you for your quick response to fix issues, well done @tilltue 

Second, there is an issue that Collections array is not updated in case of changes on photo library inside ```
public func photoLibraryDidChange(_ changeInstance: PHChange)```

This leads to albums table view shows 
1- deleted album.
2- incorrect albums' image count (in case add/delete image from an album)

Steps: 
- open camera roll view controller
- tap on top of screen to open albums table view
- re-tap on the top to close albums table view
- go to photos app to deleted an album for example "test album"
- back to camera roll view controller 
- tab on top of screen to re-open albums
- deleted album is shown inside albums table view 

@tilltue  please provide

**Comment by tilltue** [comment]
@menayousif 
Now, there is reload photos collections when is not changed current loaded collections. 
(e.g. added albums or remove.)
d6cf40d4d284ae25ed3b67aa492f7c309a93a0db
