### ISSUE TITLE
Dear Author，

### ISSUE THREAD

**Issue by brandy2015** [tilltue/TLPhotoPicker#236]
var configure = TLPhotosPickerConfigure()
        configure.fetchCollectionTypes = [(.smartAlbum, .smartAlbumAnimated)]
        configure.numberOfColumn = 3
        configure.singleSelectedMode = false
        configure.supportedInterfaceOrientations = [.all]
        configure.maxSelectedAssets = 1

OR
configure.singleSelectedMode = true

This issue happened at when I select one GIF pic. It doesn't reload cell. Waiting. Thanks

**Comment by tilltue** [comment]
Hi, @brandy2015 
I can't reproduce this.
![RPReplay_Final1573279266](https://user-images.githubusercontent.com/2108446/68523869-61920980-0302-11ea-98ea-00884f976ce9.gif)

using this options

var configure = TLPhotosPickerConfigure()
configure.fetchCollectionTypes = [(.smartAlbum, .smartAlbumAnimated)]
configure.numberOfColumn = 3
configure.singleSelectedMode = false
configure.supportedInterfaceOrientations = [.all]
configure.maxSelectedAssets = 1

**Comment by brandy2015** [comment]
I will reproduce it ASAP. Thanks ^0^

**Comment by brandy2015** [comment]
configure.singleSelectedMode = false change to 
configure.singleSelectedMode = true

**Comment by brandy2015** [comment]
![IMG_8011](https://user-images.githubusercontent.com/10484324/68684347-4e519900-05a3-11ea-948f-4bfbb1bea990.PNG)

**Comment by brandy2015** [comment]
and you will see that don't reload

**Comment by tilltue** [comment]
Thanks! I've fixed that.
