### ISSUE TITLE
photos in iCloud

### ISSUE THREAD

**Issue by hell4opt** [tilltue/TLPhotoPicker#238]
some users of my application write that they can’t add photos, I think this is due to the fact that they have them in icloud or something is connected with this, is there a solution?

**Comment by stewwan** [comment]
Same.

**Comment by randarnold** [comment]
Are you retrieving your assets via PHAsset or TLPHAsset?

With PHAsset, make sure you pass isNetworkAccessAllowed == true to PHImageManager.requestImage(...) if you want to get the cloud version.

**Comment by tilltue** [comment]
@hell4opt  @stewwan  
use this options.
isNetworkAccessAllowed

**Comment by hell4opt** [comment]
> @hell4opt @stewwan
> use this options.
> isNetworkAccessAllowed

where use this ? thx

**Comment by randarnold** [comment]
PHImageRequestOptions()

**Comment by stewones** [comment]
I'm doing that, no luck though. help?

```swift
      let imageManager = PHImageManager.default()

      let options = PHImageRequestOptions()
      options.isNetworkAccessAllowed = true
      options.isSynchronous = true
      options.resizeMode = .exact
      options.deliveryMode = .highQualityFormat

      imageManager.requestImage(for: phAsset!, targetSize: size, contentMode: .aspectFill, options: options) {
      // ...
 ```

app still crashing for older images stored in icloud
