### ISSUE TITLE
Show hidden album with all other albums

### ISSUE THREAD

**Issue by Lokemy** [tilltue/TLPhotoPicker#244]
Hello! I have already sought advice.
Tell me, how to display a hidden album with other albums?

**Comment by tilltue** [comment]
Hi, @Lokemy 
You can use this options fetchCollectionTypes
e.g. )
configure.fetchCollectionTypes = [
            (PHAssetCollectionType.smartAlbum, PHAssetCollectionSubtype.smartAlbumGeneric),
            (PHAssetCollectionType.smartAlbum, PHAssetCollectionSubtype.smartAlbumPanoramas),
            ...(whatever you want)
        ]
