### ISSUE TITLE
Video Time limitation

### ISSUE THREAD

**Issue by techhirasky** [tilltue/TLPhotoPicker#248]
var configure = TLPhotosPickerConfigure()
               configure.maxVideoDuration = 3
                configure.allowedVideo = true
                configure.allowedLivePhotos = true
                configure.allowedVideoRecording = true
                viewController.modalPresentationStyle = .fullScreen
                self.present(viewController, animated: true, completion: nil)

maxVideoDuration filter is not working for me any one help me.

**Comment by tilltue** [comment]
I can represent that. can you show me screenshot or somethings?

**Comment by techhirasky** [comment]
> @techhirasky

**Comment by techhirasky** [comment]
> Hi, @techhirasky
> I can reproduce that. can you show me screenshot or somethings?

Please check attached URL  need to add 30 sec filter


https://drive.google.com/file/d/1Xjpa_JTBIhCcaK3RQUyZnvVv8aEwN6Uj/view?usp=sharing
