### ISSUE TITLE
Picking video crashes for iOS 13

### ISSUE THREAD

**Issue by bshankar-coder** [tilltue/TLPhotoPicker#250]
func Seletct_Image(type : String)
    {
        let viewController = TLPhotosPickerViewController()
        viewController.delegate = self
        var configure = TLPhotosPickerConfigure()
        configure.numberOfColumn = 3
        configure.mediaType = (type == "image") ? PHAssetMediaType.image :PHAssetMediaType.video
        configure.usedCameraButton = false
        viewController.configure = configure
        viewController.selectedAssets = self.selectedAssets
        viewController.logDelegate = self
        if #available(iOS 13, *){
            let statusBar = UIView(frame: (UIApplication.shared.keyWindow?.windowScene?.statusBarManager?.statusBarFrame)!)
            statusBar.backgroundColor = #colorLiteral(red: 0.7450980544, green: 0.1568627506, blue: 0.07450980693, alpha: 1)
            UIApplication.shared.keyWindow?.addSubview(statusBar)
        }
        else {
            if let statusBar = UIApplication.shared.value(forKey: "statusBar") as? UIView {
                statusBar.backgroundColor = Config.App_PrimaryColor
            }
        }
        self.present(viewController, animated: true, completion: nil)
    }

func selectedPhoto(picker: TLPhotosPickerViewController, at: Int) {
        print("NewUploadVC: selected photo")
    }

Picking up Images is working fine. In iOS 13, After opening camera roll, When tapped on a video it crashes after printing "NewUploadVC: selected photo" with no other error logs. Any solution to this.

**Comment by tilltue** [comment]
@bshankar-coder 
Please can you show me crash log?
