### ISSUE TITLE
func dismissPhotoPicker(withTLPHAssets: [TLPHAsset]){} doesn't call in TLPhotosPickerViewControllerDelegate

### ISSUE THREAD

**Issue by Denismih** [tilltue/TLPhotoPicker#257]
Xcode show varning "Instance method 'dismissPhotoPicker(withTLPHAssets:)' nearly matches defaulted requirement 'dismissPhotoPicker(withPHAssets:)' of protocol 'TLPhotosPickerViewControllerDelegate'"

**Comment by brandy2015** [comment]
Same issue

**Comment by tanphamanhh** [comment]
Same issue
I see the source code of TLPhotosPickerViewControllerDelegate, there is no more func dismissPhotoPicker(withTLPHAssets: [TLPHAsset]){}

**Comment by a13xander96** [comment]
same. in the meantime you can use the completion handler method to get around this.

**Comment by dangell7** [comment]
Same error @a13xander96 how can I get the TLPH asset array as the response?

**Comment by brandy2015** [comment]
Fatal issue #255

public func dismissPhotoPicker(withTLPHAssets: [TLPHAsset]) {
self.selectedAssets = withTLPHAssets
}

didn't work

especially 2.0.9 did not work.

2.0.5 work well.

You can use 2.0.5 to constrain the pod file

**Comment by dangell7** [comment]
Fixed with shouldDismiss and return true

**Comment by intoxicated** [comment]
@brandy2015 
There are two methods, and you are calling neither of them. 
```public func dismissPhotoPicker(withPHAssets: [PHAsset]) { }```
```public func shouldDismissPhotoPicker(withTLPHAssets: [TLPHAsset]) -> Bool { return true }```

**Comment by brandy2015** [comment]
I will try that.Really thanks

**Comment by RapDevPro** [comment]
I had the same problem, then reverted back to 2.0.5 as was suggested. But now when I run my code it crashes on the line viewController.configure = configure.  If I comment out the whole configure block of code, it then crashes on self.present(viewController, animated: true, completion: nil).  Any ideas?  Code below.

`    @IBAction func takePhoto(_ sender: UIButton) {
        
        let viewController = TLPhotosPickerViewController()
        viewController.delegate = self
        viewController.didExceedMaximumNumberOfSelection = { [weak self] (picker) in
            self?.showAlert(vc: picker)
        }
        var configure = TLPhotosPickerConfigure()

        configure.numberOfColumn = 3
        configure.maxSelectedAssets = 5
        //configure.nibSet = (nibName: "CustomCell_Instagram", bundle: Bundle.main)
        viewController.configure = configure

        // Comment out the next line so that the photo-picking always starts with nothing selected; leave it to persist prior selections
        //viewController.selectedAssets = self.photoAssets1
        
        self.present(viewController, animated: true, completion: nil)
    }`

**Comment by RapDevPro** [comment]
I reverted back to 2.0.5, but now my app is crashing on the line viewController.configure = configure with Thread 1: EXC_BAD_ACCESS (code=1, address= xxx).  See code below.  If I take out the configure block of code, it then crashes on the self.present(viewController ...) line.  I have this exact code in a different app and it works fine.  Any ideas?

`        let viewController = TLPhotosPickerViewController()
        viewController.delegate = self
        viewController.didExceedMaximumNumberOfSelection = { [weak self] (picker) in
            self?.showAlert(vc: picker)
        }
        var configure = TLPhotosPickerConfigure()

        configure.numberOfColumn = 3
        configure.maxSelectedAssets = 5
        //configure.nibSet = (nibName: "CustomCell_Instagram", bundle: Bundle.main)
        viewController.configure = configure

        // Comment out the next line so that the photo-picking always starts with nothing selected; leave it to persist prior selections
        //viewController.selectedAssets = self.photoAssets1
        
        self.present(viewController, animated: true, completion: nil)`

**Comment by intoxicated** [comment]
@RapDevPro your question is unrelated to this thread. I recommend you to open an new issue separately.

**Comment by anysome** [comment]
Has to move code from
`public func dismissPhotoPicker(withPHAssets: [PHAsset]) `
to
`public func shouldDismissPhotoPicker(withTLPHAssets: [TLPHAsset]) -> Bool`

What a pity.

**Comment by ariiyu** [comment]
I think README should be updated for this change.
I opened a PR.
https://github.com/tilltue/TLPhotoPicker/pull/265
