### ISSUE TITLE
Selecting photos don't work with 2.0.10?

### ISSUE THREAD

**Issue by danqing** [tilltue/TLPhotoPicker#264]
I'm not sure what's changed since 2.0.7, but my app functioning properly in 2.0.7 no longer does in 2.0.10 - after I select photos and click Done, the picker controller gets dismissed but no images are selected.

**Comment by sm0nster** [comment]
Having same issue, debugger triggers method 
`dismissPhotoPicker(withTLPHAssets: [TLPHAsset]) `
before launching view controller instead of launching after dismissing with selected photos

**Comment by danqing** [comment]
That sounds like a breaking change @tilltue ? Is it going to stay? Would be great if semver can be adhered.

**Comment by wade-hawk** [comment]
@danqing Sorry. That breaking change was not intended.
release 2.0.11

**Comment by imtiaz191919** [comment]
Is this fixed ?

**Comment by danqing** [comment]
I think this is fixed. Closing.
