### ISSUE TITLE
Change album to "All photos"

### ISSUE THREAD

**Issue by nadyapost** [tilltue/TLPhotoPicker#272]
Hey, Is there a way to change album collection type to show all photos of the device? Right now it shows "Recents" by default.

**Comment by randarnold** [comment]
The issue is that it takes a long time to process all your albums and they are not displayed until they are all processed. The more albums you have the longer it takes (minutes in my case).

I worked on a fix for this, but haven't had time to finish it.

**Comment by nadyapost** [comment]
Thanks a lot for clearing up the air @randarnold . I'm in the beginning of my iOS journey and I really appreciate your quick response. Cheers.
