### ISSUE TITLE
Camera button disappears when set fetchCollectionTypes

### ISSUE THREAD

**Issue by nadyapost** [tilltue/TLPhotoPicker#273]
Hey, Even though I specially set `usedCameraButton` to true I can't figure out why camera button disappears once I set fetchCollectionTypes like this:  

`configure.usedCameraButton = true`
`configure.fetchCollectionTypes = [(.album, .any)]`

![image](https://user-images.githubusercontent.com/43269819/81265852-1a08f200-9087-11ea-8aab-519f537071fc.png)

**Comment by tilltue** [comment]
@nadyapost 
subtype fetch options[(.album, .any)] was not contain smart albums and then not showing if you taken a photos. (if you take a picture, saved in smart albums library.)
That's why not show camera button if using subtype fetch options.
