### ISSUE TITLE
tempCopyMediaFile() changes the extension of HEIF photos but does not convert them

### ISSUE THREAD

**Issue by EimantasMorkunas** [tilltue/TLPhotoPicker#274]
Calling `tempCopyMediaFile()` on HEIF image asset that is **not** a live photo and passing `convertLivePhotosToJPG: true` changes the file's extension to `.jpg` but doesn't actually convert it to a JPEG.

It can get really confusing if the temp file is exported and used on a platform that doesn't support HEIF.

**Comment by tilltue** [comment]
@EimantasMorkunas 
You right. I've pushed a fix for this.
