### ISSUE TITLE
Bypass of maxSelectedAssets possible

### ISSUE THREAD

**Issue by jeanmartin** [tilltue/TLPhotoPicker#275]
Using TLPhotoPicker 2.0.11.
After taking a photo with the camera it takes 1-2 seconds for the new (already selected) photo to be added to the list. If you select another one during those 1-2 seconds you can end up with more assets selected than allowed.

Specific example:

- set `maxSelectedAssets` to 5
- select 4 assets
- open camera to take a picture
- after returning quickly (before the new picture gets added to the list) select a 5th asset
- once the new photo is finally added it is also selected, you have now 6 assets selected

**Comment by tilltue** [comment]
@jeanmartin 
PHPhotoLibrary.shared().performChanges is async functions.
That's why takes time to save to photos
checked max count when callback .

And I've pushed a fix for this.
