### ISSUE TITLE
Support new photo library `Limit` authority on Xcode 12 and iOS 14 

### ISSUE THREAD

**Issue by archerx3** [tilltue/TLPhotoPicker#279]
![simulator_screenshot_545E792F-CF72-4B0F-A677-D629817D437C](https://user-images.githubusercontent.com/15372277/91252984-4d37d400-e791-11ea-884e-760f580c88c8.png)

**Comment by memamdie** [comment]
@archerx3 why was this closed? I am seeing the same issue

**Comment by crisbarril** [comment]
Same here. Will this support iOS 14?

**Comment by xiaowasly** [comment]
@archerx3 你好 请问14相册这个问题怎么解决的？这个库如何过滤掉用户没有权限的照片？非常感谢！！
