### ISSUE TITLE
Crash when use camera

### ISSUE THREAD

**Issue by tooszovski** [tilltue/TLPhotoPicker#28]
Preconditions:

1. Instantiate TLPhotosPickerConfigure with parameter includeVideos: false
2. Take a picture from Camera
3. Crash

**Comment by tilltue** [comment]
@tooszovski 
Thank you.
There was a problem in PHPhotoLibraryChangeObserver(photoLibraryDidChange).

**Comment by muhammadahsaniqbal** [comment]
It's still crashing in performBatchUpdates method on self?.collectionView.insertItems(at: inserted.map { IndexPath(item: $0+addIndex, section:0) }) while using camera to load photo.
