### ISSUE TITLE
Support Swift Package Manager

### ISSUE THREAD

**Issue by BrandonNott** [tilltue/TLPhotoPicker#284]
As of swift 5.3, Xcode 12 - SPM supports bundling resources.

Can we add support for this?

Thanks

Dup of #224

**Comment by tilltue** [comment]
@BrandonNott 
Now, you can use SPM.

**Comment by TerenzeY** [comment]
For some reasons I keep getting this.

Showing All Messages
An unknown error occurred. HTTP parser error: stream ended at an unexpected time (-1)

Anyone having the same issue?
