### ISSUE TITLE
Xcode 11 compatibility lost

### ISSUE THREAD

**Issue by crisbarril** [tilltue/TLPhotoPicker#288]
In the last release this change on the TLPhotosPickerViewController.xib file broke the compatibility with versions below Xcode 12.
<img width="841" alt="Screen Shot 2020-09-22 at 18 31 45" src="https://user-images.githubusercontent.com/9450790/93911008-23c38700-fd02-11ea-91dc-1b41f22d9a71.png">

@tilltue can you please check on this?

**Comment by grioja** [comment]
Still broken (using SPM) for me on Xcode 11.6:

> because TLPhotoPicker >=2.1.1 contains incompatible tools version and root depends on TLPhotoPicker 2.1.2, version solving failed.
