### ISSUE TITLE
iCloud Photo Library

### ISSUE THREAD

**Issue by vogttho** [tilltue/TLPhotoPicker#29]
It looks as if photos are not loaded from iCloud Photo Library. It only works if I open the photo in photos app first and download the original photo. After that I can select it in TLPhotoPicker.

**Comment by tilltue** [comment]
unfortunately there's not supported icloud photo library. now.
it'll be soon. sorry.

**Comment by biscottigelato** [comment]
2nding this problem.

**Comment by tilltue** [comment]
b7e32989e07001cd8649175375888b069838b9ce
