### ISSUE TITLE
The layout is broken on iPhone 12 and iPhone 12 Pro

### ISSUE THREAD

**Issue by dataich** [tilltue/TLPhotoPicker#292]
On iPhone 12 and iPhone 12 Pro, the default layout is broken like screenshots. Those screenshots can be reproduced using Example project in this repository.

- NG
  - iPhone 12
  - iPhone 12 Pro
- OK
  - iPhone 12 Pro Max
  - iPhone 12 Mini

I guess this happens from calculating item width using the view frame's width.

<img title="iPhone 12 Mini" src="https://user-images.githubusercontent.com/15887/97165606-5233f680-17c7-11eb-9e30-adc24eaba100.png" width="300">
<img title="iPhone 12 Pro Max" src="https://user-images.githubusercontent.com/15887/97165610-53fdba00-17c7-11eb-9f0a-5495effbd806.png" width="300">
<img title="iPhone 12 Pro" src="https://user-images.githubusercontent.com/15887/97165616-552ee700-17c7-11eb-8802-b9cc9e07b58a.png" width="300">
<img title="iPhone 12" src="https://user-images.githubusercontent.com/15887/97165621-56601400-17c7-11eb-99b6-a2a962938458.png" width="300">

**Comment by tilltue** [comment]
@dataich 
👍 Nice catch, thanks!
