### ISSUE TITLE
Unhandled file warnings when importing via SPM

### ISSUE THREAD

**Issue by jacobh0** [tilltue/TLPhotoPicker#298]
![Screen Shot 2020-11-18 at 2 26 47 PM](https://user-images.githubusercontent.com/89693/99595832-34167c00-29aa-11eb-9c4f-7d9bcfffe7f1.png)

On version 2.1.2 fyi

**Comment by marinofaggiana** [comment]
Exactly +1

**Comment by tylerbGurutech** [comment]
Still a problem on 2.1.3

**Comment by tilltue** [comment]
Fixed This
