### ISSUE TITLE
diff: /Podfile.lock: No such file or directory

### ISSUE THREAD

**Issue by cbangchen** [tilltue/TLPhotoPicker#3]
<img width="709" alt="2017-05-15 12 29 09" src="https://cloud.githubusercontent.com/assets/11977680/26042661/b5a6a914-3969-11e7-8670-4477a3a04e26.png">

Got this and have no clue to solve it out. Did anybody get the same issue before?

**Comment by tilltue** [comment]
Then there's a problem with Cocoapods in your project.  Sometimes cocoapods can get out of sync and you need to re-initiate cocoapods. You should be able to resolve this error by:

1. Deleting the Podfile.lock file in your project folder
2. Deleting the Pods folder in your project folder
3. Execute 'pod install' in your project folder
4. Do a "Clean" in Xcode
5. Rebuild your project

**Comment by cbangchen** [comment]
I already tried it at the very beginning, but it didn't work out. Any other ideas?

**Comment by fangyuxi** [comment]
@cbangchen 
update your cocoapods to newest version
and run pod setup

and ..

Deleting the Podfile.lock file in your project folder
Deleting the Pods folder in your project folder
Execute 'pod install' in your project folder
Do a "Clean" in Xcode
Rebuild your project

**Comment by cbangchen** [comment]
@tilltue @fangyuxi, thx, update operation works.

**Comment by ivancho2802** [comment]
solved for me: XCODE, IOS, CORDOVA y IONIC

1 - in xcode change value of $(SRCROOT) for you root project in xcode las var of config build in 

2 - changed var in this clic in the plus of up: enter image description here

nota: root project is: location of my project and location where use pod this my firs question thank for watching

Images and details in:
https://stackoverflow.com/questions/40095677/how-can-i-add-a-symbol-like-srcroot-to-use-in-an-xcode-projects-build-settin/51971532#51971532
