### ISSUE TITLE
Can we change Done text and Cancel text color change

### ISSUE THREAD

**Issue by MasamMahmood** [tilltue/TLPhotoPicker#307]
I haven't found the property for changing `Done` text color or `Cancel` text color.

`var configure = TLPhotosPickerConfigure()
        configure.doneTitle = "Done"
        configure.cancelTitle = "Cancel"
        configure.tapHereToChange = "Tap here to change"
        configure.numberOfColumn = 3
        configure.maxSelectedAssets = 2
        configure.selectedColor = .orange`

**Comment by IvanBasay** [comment]
@MasamMahmood 
**Try this**
imagePicker.cancelButton.setTitleTextAttributes([NSAttributedString.Key.foregroundColor: UIColor.black], for: .normal)

**Comment by MrFuFuFu** [comment]
```
        viewController.doneButton?.tintColor = UIColor.black
        viewController.cancelButton?.tintColor = UIColor.black
```

**Comment by MasamMahmood** [comment]
@MrFuFuFu Thank you.
