### ISSUE TITLE
iPhone 12 display issue

### ISSUE THREAD

**Issue by Razanajam** [tilltue/TLPhotoPicker#317]
On iPhone 12 opening a 
gallery to share images/videos giving me 2 columns instead of 3, can you please check.

See attachment.
![image](https://user-images.githubusercontent.com/26906275/130577252-d37727f8-8510-4ccf-8a6c-24132e808d23.png)

**Comment by DrashtiJaviya-Openxcell** [comment]
I am facing same issue

**Comment by tilltue** [comment]
<img width="471" alt="스크린샷 2021-11-26 오전 2 00 34" src="https://user-images.githubusercontent.com/2108446/143480129-d98f6a7d-cbef-4630-b128-285d9ca063c3.png">
I cannot be reproduced that ( ios 15 , iPhone 12 simulator )

**Comment by delmarz** [comment]
![iphone13](https://user-images.githubusercontent.com/7381514/143965985-fe53e4bf-f751-41dc-8aac-16735a266a7e.jpg)


Im using xcode 13.1 running iPhone 13 (ios 15). Same issue I am facing.

**Comment by Razanajam** [comment]
Please test on device, not simulator, its fine on simulator

**Comment by tilltue** [comment]
@Razanajam 
This might be the problem.
``` swift 5
        let width = floor((self.view.frame.size.width - (self.configure.minimumInteritemSpacing * (count-1))) / count)
        self.thumbnailSize = CGSize(width: width, height: width)
        layout.itemSize = self.thumbnailSize
//      layout.minimumInteritemSpacing = 0
->      layout.minimumInteritemSpacing = self.configure.minimumInteritemSpacing
        layout.minimumLineSpacing = self.configure.minimumLineSpacing
```
chages : https://github.com/tilltue/TLPhotoPicker/pull/312
other changes : https://github.com/tilltue/TLPhotoPicker/commit/89f924e7a47fefc57c7771e2d49864615f9ac0d8

**Comment by tilltue** [comment]
@Razanajam I fixed it. v2.1.8  Please check it out. 🙏

**Comment by Razanajam** [comment]
@tilltue Thankyou very much, its working now.
