### ISSUE TITLE
Picker auto-plays videos with sound

### ISSUE THREAD

**Issue by biscottigelato** [tilltue/TLPhotoPicker#32]
Picker auto-plays videos as they are selected in the thumbnail state, which I don't mind and I think is configurable anyways. However the audio plays as well, and I don't see any audio related configuration in the Configuration structure? Please advise. Thanks!

**Comment by tilltue** [comment]
add configure option: autoplay, mute audio. 4f29c45fdd97a9e7b7319ee0cf20c7088aefdc35
