### ISSUE TITLE
2.1.5 is not patch version!

### ISSUE THREAD

**Issue by stoletnaedine** [tilltue/TLPhotoPicker#325]
Hi. I updated my pods repo (Installing TLPhotoPicker 2.1.5 (was 2.1.4)) and my project was broken!
If you delete public properties (or functions) in you lib, that mean major version (3.0.0), not patch.

**Comment by tilltue** [comment]
Sorry. I think it should work now. I've pushed a fix for this. v2.1.6
revert #320
