### ISSUE TITLE
Unable to localize strings

### ISSUE THREAD

**Issue by sroymeetup** [tilltue/TLPhotoPicker#326]
Version 2.1.5 breaks the ability to provide custom localizations to TLPhotosPickerConfigure.

I see that you localized the strings, but the list of built-in languages doesn't match the languages we need in our app. Previously we were able to provide the strings we wanted. Now TLPhotosPickerConfigure appears to load strings from its bundle and I don't see a way around it.

A solution would be to keep the old properties, and just localize the defaults.

```swift
public var tapHereToChange = NSLocalizedString("Tap here to change", bundle: Bundle(for: Self.self), comment: "")
```

(As someone else pointed out, this is an API change so shouldn't be a mere maintainance version bump. This broke our build.)

**Comment by baronha** [comment]
+1

**Comment by sroymeetup** [comment]
Thank you!
