### ISSUE TITLE
2.1.6 not available in CocoaPods

### ISSUE THREAD

**Issue by sroymeetup** [tilltue/TLPhotoPicker#328]
You made a fix for issue #326 but I still don't see version 2.1.6 in Cocoapods. It insists that 2.1.5 is the latest so our project is stuck at using 2.1.4 since we need to be able to localize the strings.

**Comment by jdangerslater** [comment]
+1

**Comment by sroymeetup** [comment]
I see 2.1.6 in Cocoapods now. Thanks!
