### ISSUE TITLE
Customize camera image cell with xib

### ISSUE THREAD

**Issue by testfooyy** [tilltue/TLPhotoPicker#33]
I want to customize the camera image cell with xib.
I want you to add a setting that allows you to paste xib that you made in the camera cell part

I'd like to customize it like LINE app
https://video.twimg.com/ext_tw_video/920328582341079040/pu/vid/720x1280/95BpKP3xqc2YNvsT.mp4

**Comment by tilltue** [comment]
@testfooyy 
used custom camera cell 
see the example 
https://github.com/tilltue/TLPhotoPicker/blob/master/Example/TLPhotoPicker/CustomCameraCell.swift
![Like Line](Images/custom_cameracell.gif)
