### ISSUE TITLE
New config options

### ISSUE THREAD

**Issue by logicsb** [tilltue/TLPhotoPicker#35]
Hi, this is an awesome component. 
Can you add some options like: support to record video, maxVideoDuration (in video record and in video selection with duration predicate)?

Thanks

**Comment by tilltue** [comment]
Sure, Are You need just one option? -> 'maxVideoDuration'

**Comment by logicsb** [comment]
Yep. maxVideoDuration but this method should be affect video recording and filter videos from camera roll via predicate filter. It's possible?
