### ISSUE TITLE
Is it possible to get the images path?

### ISSUE THREAD

**Issue by Ziyad33** [tilltue/TLPhotoPicker#36]
I want to upload the images I get to the Firebase, and based on [Firebase docs](https://firebase.google.com/docs/storage/ios/upload-files?authuser=0), I need to get the images location on the device.

How can I get the path of the selected images in `var selectedAssets = [TLPHAsset]()`?
I went through the methods of `selectedAssets`, i could find functions like `selectedAssets.count` and `selectedAssets[0].originalFileName` but nothing were related to the file path.

How can I get the files path in the device?

Any guidance will be appreciated

**Comment by tilltue** [comment]
@Ziyad33 
https://github.com/tilltue/TLPhotoPicker/issues/22

You have to copy temporary file. ( don't forget remove file after uploaded )

**Comment by Ziyad33** [comment]
@tilltue Thank you, I am looking into it now

**Comment by Ziyad33** [comment]
in this line:
`   guard let localURL = writeURL,let mimetype = fileName.MIMEType() else { return nil }`

it says that 

> value of type 'String' has no member 'MIMEType'

and in the last line here:
  `completion(url?.fileSize() ?? -1)`
it says:

> value of type 'URL' has no member 'fileSize'

**Comment by Ziyad33** [comment]
I am trying to look for a solution at the mean time but is those functions actually available in the String and URL classes? thats my question

**Comment by Ziyad33** [comment]
I found an answer on Stackoverflow [here](https://stackoverflow.com/questions/38183613/how-to-get-url-for-a-phasset). But I didn't know how to use apply it, was wondering if you can guide me if the solution on Stackoverflow is correct.

Sorry for the inconvenience

**Comment by tilltue** [comment]
@Ziyad33 
You have to implementation write to image temporary file. like [This](https://www.hackingwithswift.com/example-code/media/how-to-save-a-uiimage-to-a-file-using-uiimagepngrepresentation)
#22 is in video case.
