### ISSUE TITLE
Video file with size limitation

### ISSUE THREAD

**Issue by polaris0227** [tilltue/TLPhotoPicker#40]
Hi, thanks for you to share this library.
I found that I can choose videos with duration limitation.
Would you like to let me know if it is possible to pick videos by size limitation?
eg. I want to choose videos which is smaller than 10 MB...
I'll appreciate if you can help me.
Thanks again.

**Comment by tilltue** [comment]
@polaris0227 
[PHFetchOptions Apple Document Link](https://developer.apple.com/documentation/photos/phfetchoptions)
PHFetchOptions is not support size limitation.

Another way, Check Video file size after did selected assets.

839f9ea3d1107713c837449f87b45977bf2fc5a5

Use this. 
public func videoSize(options: PHVideoRequestOptions? = nil, completion: @escaping ((Int)->Void))

**Comment by polaris0227** [comment]
Thank you for your reply.
It was very helpful.
Thanks again.
