### ISSUE TITLE
is downloading a video from ICloud Supported ? 

### ISSUE THREAD

**Issue by specc** [tilltue/TLPhotoPicker#42]
I am using ICloud to store my old videos in camera roll. I don't see a method for getting video from ICloud. I only see cloudImageDownload(progressBlock: @escaping (Double) -> Void, completionBlock:@escaping (UIImage?)-> Void ) -> PHImageRequestID?

Please let me know how I can download cloud video.

**Comment by tilltue** [comment]
@specc 

Apple Document : request of video asset
https://developer.apple.com/documentation/photos/phimagemanager

https://developer.apple.com/documentation/photos/phimagemanager/1616981-requestexportsession

**Comment by specc** [comment]
ah ok I will try it out. Is there a flag that will tell me whether a video is from iCloud or not ?

**Comment by tilltue** [comment]
@specc 
Use this.
public func tempCopyMediaFile(progressBlock:((Double) -> Void)? = nil, completionBlock:@escaping ((URL,String) -> Void)) -> PHImageRequestID?

76a280e50a751df370a0a979fbbd7b3f9cda281d
