### ISSUE TITLE
Cropping pictures

### ISSUE THREAD

**Issue by andrezacds** [tilltue/TLPhotoPicker#43]
Hi!! I liked TLPhotoPicker, but I need to be able to crop pictures... Do you have any intention to add this feature?

**Comment by tilltue** [comment]
I think If you want cropped image, you better use other framework than I did.
Like this : https://github.com/TimOliver/TOCropViewController

**Comment by andrezacds** [comment]
I need to be able to select multiple pictures and then crop them. Does your framework allow that?

**Comment by tilltue** [comment]
I'm afraid not.
