### ISSUE TITLE
Support selected Gif and LivePhoto.

### ISSUE THREAD

**Issue by tilltue** [tilltue/TLPhotoPicker#46]
Support selected Gif file.
It can be get gif file. and Live Photos.

**Comment by tilltue** [comment]
76a280e50a751df370a0a979fbbd7b3f9cda281d

**Comment by brandy2015** [comment]
Hi,dear author,
How can I get GIf only ?

**Comment by DanielZanchi** [comment]
> Hi,dear author, How can I get GIf only ?

Looking for the same thing. Did you find anything?
