### ISSUE TITLE
App crashes when switching to video recording mode. 

### ISSUE THREAD

**Issue by rizwan95** [tilltue/TLPhotoPicker#47]
The app crashes when we select video recording from the library in the sample project. You have to add  Microphone access permission in the .plist file. 

Here is the crash log

"This app has crashed because it attempted to access privacy-sensitive data without a usage description.  The app's Info.plist must contain an NSMicrophoneUsageDescription key with a string value explaining to the user how the app uses this data."

**Comment by tilltue** [comment]
@rizwan95 
Thank you. Fixed that.

**Comment by rizwan95** [comment]
Great !
