### ISSUE TITLE
How can you start in the videos section

### ISSUE THREAD

**Issue by benmoadw** [tilltue/TLPhotoPicker#48]
Hi, thank you so much for doing this framework.

I was wondering how can I present the viewcontroller not in the photos section but in the Videos one?

Thank you.

**Comment by tilltue** [comment]
@benmoadw 
You can use PHAssetMediaType options.
...
configure.mediaType = .video
...

[Configure Options](https://github.com/tilltue/TLPhotoPicker#customize)
public var mediaType: PHAssetMediaType? = nil

**Comment by benmoadw** [comment]
Wow, I knew it was a dumb question, thank you for your help.

If you can help me with another thing... I'll start the framework with only videos and I'll put max item selection to one. What do I have to do if the user picked a video and then it's the wrong video and will pick another video, instead of prompting the alert view with the exceed message how can I replace the option he picked with the new one. Thank you so much again for your help.

**Comment by benmoadw** [comment]
Another thing I forgot, sorry, How can I limit the size or duration of the videos I show to the user through the framework, is there a way for me to click a video and if it is more than 10 secs show a alert view saying you have to pick a video with less duration? Thank you.

**Comment by benmoadw** [comment]
public var maxVideoDuration:TimeInterval? = nil
    public var autoPlay = true
    public var muteAudio = true
    public var singleSelectedMode = false

Somehow I feel like this are the things I'm looking for but when I try to use them by using configure. xcode won't show me those options.

**Comment by benmoadw** [comment]
Im using version 1.2.7 of your framework since I haven't migrate yet to swift 4, I don't know if this helps.

**Comment by tilltue** [comment]
@benmoadw 
I tried that. But, I can't migration current source convert version for swift 3.2. That is too much changed source code. Sorry.
