### ISSUE TITLE
Can't get the real size of videos in album?

### ISSUE THREAD

**Issue by AniOSDeveloper** [tilltue/TLPhotoPicker#50]
In TLPHAsset struct, I find a function named `videoSize(options:,completion:((Int)->Void)) ` ,  which is to  get video size of PHAsset, but I find the sizes of  videos are -1 after calling it.
After checking the function,  I find the `url` is always nil, that is to say neither of the if nor the else branch is entered.

BTW
plateforms are Xcode 9.2 and iOS 11.2.

**Comment by tilltue** [comment]
Can you try again? I did change size check implementation.
76a280e50a751df370a0a979fbbd7b3f9cda281d

**Comment by AniOSDeveloper** [comment]
Now it can get the size of videos.
It seems that the dict of `resource` works, but the url of any video is still nil.
Can you help check why the `avasset`  in the  completion of `PHImageManager.default().requestAVAsset(forVideo: phAsset, options: options)`  is nil?

**Comment by tilltue** [comment]
@AniOSDeveloper 
I guess default videoSize function use "PHVideoRequestOptions = nil". That's why can't getting AVURLAsset. If that contents is iCloud contents needs network allowed options. You should read this link and try that.
[PHVideoRequestOptions](https://developer.apple.com/documentation/photos/phvideorequestoptions)

**Comment by tilltue** [comment]
@AniOSDeveloper 
Try use this branch.
https://github.com/tilltue/TLPhotoPicker/tree/agit

**Comment by AniOSDeveloper** [comment]
Thanks.
I have tried several combinations to set `PHVideoRequestOptions`, and finally found when setting the follow option, `PHImageManager.default().requestAVAsset(forVideo: phAsset, options: options)` could get the real size of given PHAsset:
`        let customOption = PHVideoRequestOptions.init()
        customOption.version = PHVideoRequestOptionsVersion.current
        customOption.deliveryMode = PHVideoRequestOptionsDeliveryMode.automatic
        customOption.isNetworkAccessAllowed = false
`
