### ISSUE TITLE
Itunes synced images

### ISSUE THREAD

**Issue by Hiren95** [tilltue/TLPhotoPicker#52]
Hello ,

I am not getting album which is synced through itunes.

**Comment by Ilesh** [comment]
Hello @Nirma @intmain @marciliojrs @tiny2n, Hope you are doing great !! I am facing one issue in the library for not showing my iTunes synced images. Can you please help me to resolve it.

**Comment by tilltue** [comment]
You can use option for get all album.
```swift3
public struct TLPhotosPickerConfigure {
    ///...
    public var getAllAlbum = false // get all album (default: get smart album)
}
```
012f3c6ca8ee588fc2ac60cbfc30c4ca4d22733d
