### ISSUE TITLE
Support for Objective C projects.

### ISSUE THREAD

**Issue by rizwan95** [tilltue/TLPhotoPicker#55]
Is it possible to support the integration of TLPhotoPicker with Objective C projects as well? We are unable to use TLPHAssets in Objective C class because it is a struct and Swift structs are not accessible via Objective C classes.

**Comment by tilltue** [comment]
Sorry not now. I don't have any plan.

**Comment by rizwan95** [comment]
I have written a wrapper class for supporting Objective-C projects. I would be happy to contribute to the repo.

**Comment by balkarov** [comment]
@rizwan95 could you create repo? And send link please

**Comment by rizwan95** [comment]
Yes Sure! I will do it right away and update you :)

**Comment by balkarov** [comment]
Thank you! I will wait ;)

**Comment by rizwan95** [comment]
Hi, here is the Objective C support for this awesome library. https://github.com/rizwan95/TLPhotoPicker

Feel free to try it out and give suggestions.

**Comment by balkarov** [comment]
@rizwan95 hello! 
Thank you! Maybe you will create pull request to main library?

**Comment by rizwan95** [comment]
Yes I did create a pull request from the main library and then added my files in it. Feel free to check it out.

**Comment by balkarov** [comment]
No no, I mean create pr from your repo to this [repo](https://github.com/tilltue/TLPhotoPicker)

**Comment by rizwan95** [comment]
Okay Sure I will.

**Comment by Ihernandezpi** [comment]
> Okay Sure I will.

Hello! Did you send the pulll request?  I did not founded the class wrapper in your fork repo. Please help me. Thanks in advance

**Comment by rizwan95** [comment]
> > Okay Sure I will.
> 
> Hello @rizwan95 ! Did you send the pulll request? I did not founded the class wrapper in your fork repo. Please help me. Thanks in advance

I still have to do some changes to the code. Once I have done I will submit a PR. Give me a couple of days.

**Comment by rizwan95** [comment]
Here is the PR with Objective-C support. 
https://github.com/tilltue/TLPhotoPicker/pull/166

@Ihernandezpi

**Comment by rizwan95** [comment]
@tilltue it would be great if you review the PR. It would be beneficial for the developers who want to use your library in their Objective-C project.

**Comment by Ihernandezpi** [comment]
@rizwan95 thankyou. I appreciate it.
