### ISSUE TITLE
Localize the strings in TLPhotosPickerViewController.swift

### ISSUE THREAD

**Issue by rizwan95** [tilltue/TLPhotoPicker#57]
The strings like "Camera Roll", "Tap here to change", etc need to be localized.

**Comment by tilltue** [comment]
@rizwan95 
```swift3
public struct TLPhotosPickerConfigure {
    public var defaultCameraRollTitle = "Camera Roll"
    public var tapHereToChange = "Tap here to change"
}
```

**Comment by rizwan95** [comment]
You should be using NSLocalizedString right?

**Comment by tilltue** [comment]
@rizwan95 
If you want localized string, you modify configure option.
en -> configure.defaultCameraRollTitle = "Camera Roll"
fr -> configure.defaultCameraRollTitle = "rouleau de caméra"

**Comment by rizwan95** [comment]
If we use NSLocalizaedString, the system will adapt accordingly to the language selected in the device.

For example,

//Your struct
 public struct TLPhotosPickerConfigure {
    public var defaultCameraRollTitle = NSLocalizedString("tlphotopicker.common.camerarolltext", comment: "Camera roll text string")
    public var tapHereToChange = NSLocalizedString("tlphotopicker.common.taphereText", comment: "Tap here to change text string")
}

// Localized strings files

Localizable.strings(English)
"tlphotopicker.common.taphereText" = "Camera Roll";
Localizable.strings(French)
"tlphotopicker.common.taphereText" = "rouleau de caméra";

So, this will dynamically change the text according to the language selected by the user in the device. 
:)

**Comment by tilltue** [comment]
Sure. I don't want to Localized string in framework bundle. I think that was user's role. Isn't it?

**Comment by rizwan95** [comment]
I think you should provide a Localized string in the bundle because production apps support a lot of languages so it would be great if the framework is also localized. This will give a benefit to the framework. People will start using it more. :)
