### ISSUE TITLE
Duration and video size preset configuration for iCloud video download 

### ISSUE THREAD

**Issue by specc** [tilltue/TLPhotoPicker#60]
Hi, is there a way to change the duration and the quality of the avExportSession from requestExportSession?

**Comment by tilltue** [comment]
@specc 
duration : https://github.com/tilltue/TLPhotoPicker/issues/35
quality : https://developer.apple.com/documentation/photos/phvideorequestoptionsdeliverymode

**Comment by specc** [comment]
For duration, if I have a 1:30 minute video, I want to export it as a 15 seconds video. How do I do that?
if I set maxVideoDuration to 15, it seems to now show video longer than 15 seconds. 

For quality, I want to use AVAssetExportPreset960x540 to export my video to 960x540 resolution.

**Comment by tilltue** [comment]
@specc 
Crop video opensource
https://github.com/prynt/PryntTrimmerView
