### ISSUE TITLE
Add TLPhotosPickerViewController Subclass Support

### ISSUE THREAD

**Issue by efremidze** [tilltue/TLPhotoPicker#63]
Since `init(coder)` is not implemented, I can't customize the xib to replace the navigation bar with my custom one. It would be nice to have the option to subclass (with a custom xib). I can't find any other way to adjust the navigation bar. Also the titleView should be a button instead of a view with a tap gesture.

```
required public init?(coder aDecoder: NSCoder) {
    fatalError("init(coder:) has not been implemented")
}
```

**Comment by tilltue** [comment]
If you want to custom navigationBarItem, used custom TLPhotosPickerViewController xib.
But that would inconvenience. sorry.
There is not enough custom option for navigationBarItem. sorry.
