### ISSUE TITLE
orderLabel not reloading when seleted and scroll up/down (screenshot)

### ISSUE THREAD

**Issue by linhbt** [tilltue/TLPhotoPicker#64]
first: select photo 1, 2, scroll down select photo 3
second: scroll up : select photo 4, deselect photo2 , scoll down -> orderLabel not reloading 
screen shot
![issue](https://user-images.githubusercontent.com/22141788/34661757-59abb160-f47e-11e7-9620-e84bee4ecb4c.png)

fixed:  Using reloadItem solved it
Tks!

**Comment by tilltue** [comment]
Good!
