### ISSUE TITLE
How to allow only Video

### ISSUE THREAD

**Issue by ErAshu** [tilltue/TLPhotoPicker#67]
How to allow only video. I don't have to show photo but only video?

By the below code i can restrict video.
`viewController.configure.allowedVideo = false`

is there any method like this so that i can restrict Photo

Thanks

**Comment by tilltue** [comment]
@ErAshu 
```swift3
...
// configure options
public var mediaType: PHAssetMediaType? = nil
...

configure.mediaType = .image
```

**Comment by ErAshu** [comment]
@tilltue  
Thanks... its done.
