### ISSUE TITLE
video and LivePhoto playback display error on iOS 10.3.2 iPhone 7

### ISSUE THREAD

**Issue by fangyuxi** [tilltue/TLPhotoPicker#7]
hi

video and LivePhoto playback

only has audio track 

cell can't display video or livephoto

**Comment by tilltue** [comment]
I don't know what the problam is.
Can you show me screenshot or anything else?

**Comment by fangyuxi** [comment]
@tilltue 
Sorry, my English is very poor .
I want to say , Video and LivePhoto can't preview(but only has audio track) in cell,on my iPhone.

**Comment by dev3ios** [comment]
Hi I have the same problem
I have iPhone 6 and when select video it doesn't play video but only audio

And please tell me can I Disable playback video?

**Comment by tilltue** [comment]
@dev3ios 
How can i make audio type phasset contents?

**Comment by tilltue** [comment]
bug fix.
livephoto audio mute.
b7e32989e07001cd8649175375888b069838b9ce
