### ISSUE TITLE
Unable to install via CocoaPods

### ISSUE THREAD

**Issue by cwestMobile** [tilltue/TLPhotoPicker#72]
I'm getting the following error...

Unable to find a specification for 'TLPhotoPicker'

Ideas?

**Comment by tilltue** [comment]
@cwestMobile 
Podfile
```
platform :ios, '9.1'
```

**Comment by cwestMobile** [comment]
Yeah I put the following in my podfile...

platform :ios, '9.1'
pod "TLPhotoPicker"

Still getting the error.

**Comment by cwestMobile** [comment]
If anybody else has this. I did a 'pod repo update' and it fixed the issue. Thanks.
