### ISSUE TITLE
[ImageManager] Unable to load image data

### ISSUE THREAD

**Issue by crickabhi** [tilltue/TLPhotoPicker#78]
When i switch between albums, there are no images shown
![img_19d611cc9c59-1](https://user-images.githubusercontent.com/10657329/35611302-a2705d38-068a-11e8-85a9-5402fa9f45ca.jpeg)

**Comment by tilltue** [comment]
@crickabhi 
Sorry.
Side effect : https://github.com/tilltue/TLPhotoPicker/pull/75
Revert PR
