### ISSUE TITLE
Please adjust dismiss method should be process beside completion

### ISSUE THREAD

**Issue by buiminhhuy** [tilltue/TLPhotoPicker#8]
fileprivate func dismiss(done: Bool) { 
        self.dismiss(animated: true) {
            if done {
                self.delegate?.dismissPhotoPicker(withPHAssets: self.selectedAssets.flatMap{ $0.phAsset })
                self.delegate?.dismissPhotoPicker(withTLPHAssets: self.selectedAssets)
                self.completionWithTLPHAssets?(self.selectedAssets)
                self.completionWithPHAssets?(self.selectedAssets.flatMap{ $0.phAsset })
            }else {
                self.delegate?.photoPickerDidCancel()
                self.didCancel?()
            }
        }
    }

**Comment by tilltue** [comment]
@buiminhhuy 
Can you explain why dismiss method should in process completion block?
How about this?

public protocol TLPhotosPickerViewControllerDelegate: class {
    func dismissPhotoPicker(withPHAssets: [PHAsset])
    func dismissPhotoPicker(withTLPHAssets: [TLPHAsset])
    func dismissComplete() // completion dismiss
    func photoPickerDidCancel()
    func didExceedMaximumNumberOfSelection(picker: TLPhotosPickerViewController)
}

**Comment by buiminhhuy** [comment]
Hi @tilltue,
I got issue when get top ViewController after dismiss to present newViewController, my top ViewController now is TLPhotosPickerViewController, when dismiss action does not yet complete, so newViewController auto call dismiss (I don't know as so).

**Comment by tilltue** [comment]
@buiminhhuy 
But dismissviewcontroller completion block has a couple second delay.
```swift
public protocol TLPhotosPickerViewControllerDelegate: class {
    func dismissPhotoPicker(withPHAssets: [PHAsset])
    func dismissPhotoPicker(withTLPHAssets: [TLPHAsset])
    func dismissComplete()
    func photoPickerDidCancel()
    func didExceedMaximumNumberOfSelection(picker: TLPhotosPickerViewController)
}
open var dismissCompletion: (() -> Void)? = nil
```
you can use 'dismissComplete() delegate or dismissCompletion closure' whatever you want.

**Comment by buiminhhuy** [comment]
Because I need value withTLPHAssets after select, If work fine I will use it, Thanks you.

**Comment by tilltue** [comment]
659058d6f5669643d5343a43230d02b1fbfda260

**Comment by buiminhhuy** [comment]
work fine thanks @tilltue
