### ISSUE TITLE
problem with updating selecting indexes

### ISSUE THREAD

**Issue by felixjichao** [tilltue/TLPhotoPicker#80]
Within orderUpdateCells(), only the indexes within collectionView.indexPathsForVisibleItems will be updated, so the indexes out of screen may be wrong. 
![image](https://user-images.githubusercontent.com/17485165/35763388-29e91940-0860-11e8-81b6-dd19b627101a.png)

**Comment by tilltue** [comment]
UICollectionView DataSource is sometimes not called "cellForItemAt:" when use Prefetch option enabled.
ordered update at UICollectionViewDelegate "willDisplay:"

**Comment by tilltue** [comment]
BTW Thanks to your bug report. :)
I thought people not using 'useprefetch' options.
