### ISSUE TITLE
asking for extType is time-consuming

### ISSUE THREAD

**Issue by felixjichao** [tilltue/TLPhotoPicker#81]
Because I need to tell if a photo is an image is in ".gif" format, I call extType() within cellForItemAt.
But I found the the collectionView got stuck when scrolling fast.
Is there another way to obtain file format more efficient?

(you can simply call asset.extType() within cellForItemAt to reproduce it)

**Comment by tilltue** [comment]
https://developer.apple.com/documentation/photos/phassetresource
``` swift3
    public func extType() -> ImageExtType {
        var ext = ImageExtType.png
        if let fileName = self.originalFileName, let extention = URL(string: fileName)?.pathExtension.lowercased() {
            ext = ImageExtType(rawValue: extention) ?? .png
        }
        return ext
    }
    
    public var originalFileName: String? {
        get {
            guard let phAsset = self.phAsset,let resource = PHAssetResource.assetResources(for: phAsset).first else { return nil }
            return resource.originalFilename
        }
    }
```

I think, you have to do 'PHAssetResource.assetResources(for: phAsset)' background queue.
