### ISSUE TITLE
Deselect prior-selected phassets

### ISSUE THREAD

**Issue by RapDevPro** [tilltue/TLPhotoPicker#82]
LOVE TLPhotoPicker! It's great! 

The only thing I can't figure out is how to deselect phassets that were selected in a prior photo-picking session.  For example, if I have two phassets chosen, 1 & 2, then hit Done, when I come back into picking photos, I want none chosen, not the 1 & 2 from my prior session.  I closely searched through all the issues and didn't see anything that addressed this; sorry if I missed something.

I thought that this might be a configure option, but I can't find one that applies. Any help appreciated!

**Comment by tilltue** [comment]
@RapDevPro 
For Example
https://github.com/tilltue/TLPhotoPicker/blob/master/Example/TLPhotoPicker/ViewController.swift
```swift 3
et viewController = CustomPhotoPickerViewController()
        viewController.delegate = self
        viewController.didExceedMaximumNumberOfSelection = { [weak self] (picker) in
            self?.showExceededMaximumAlert(vc: picker)
        }
        var configure = TLPhotosPickerConfigure()
        configure.numberOfColumn = 3
        viewController.configure = configure
        //viewController.selectedAssets = self.selectedAssets <- ' Do not set selectedAssets.'

        self.present(viewController, animated: true, completion: nil)
```

**Comment by RapDevPro** [comment]
Thank you! Don't know how I missed that.
