### ISSUE TITLE
Add location to photos taken with camera

### ISSUE THREAD

**Issue by RapDevPro** [tilltue/TLPhotoPicker#83]
Thanks again for TLPhotoPicker. I'm having one more issue -- when I take a photo with the Camera option (upper left-hand cell), that photo does not include the location data (latitude and longitude) of where the photo was taken. Within my app, I ask for and receive approval to do location tracking.

Is there a configuration setting I'm missing that will enable capturing the camera's location when TLPhotoPicker invokes the camera?  

Here is a snippet of my code that accesses the array returned in dismissPhotoPicker(withTLPHAssets: [TLPHAssets]):

// START
if let asset = self.photoAssets1[i].phAsset {
     if let location = asset.location {
          print ("Photo\(i+1).jpg Latitude, Longitude: \(location.coordinate.latitude), \(location.coordinate.longitude)"
      } else {
          print ("Photo\(i+1).jpg has no latitude-longitude")
      }
}
// END

For every photo that I take with the TLPhotoPicker camera, the photo has no location data.  Thanks for any help on this.

**Comment by tilltue** [comment]
It seems like Apple doesn't include the location to the metadata to images taken with the Camera from the UIImagePicker.  ;(

https://stackoverflow.com/questions/20105571/trying-to-pull-gps-metadata-from-uiimagepickercontroller-but-nslog-shows-null

http://ioscake.com/reading-the-gps-data-from-the-image-returned-by-the-camera-in-ios-iphone.html
