### ISSUE TITLE
Only Camera Roll is being listed and no other photo album is listed in iOS 11.0.2

### ISSUE THREAD

**Issue by rizwan95** [tilltue/TLPhotoPicker#86]
The library lists only "Camera Roll" folder in iOS 11.0.2 but not other folders. In other OS versions, it lists all the folders. 

Please see the attached images. 
![img_0034](https://user-images.githubusercontent.com/10910174/37018892-10ef5f68-213c-11e8-99c9-8b5037b7e28c.PNG)

**Comment by nadyapost** [comment]
This issue has been closed without a solution @rizwan95 how did you manage to fix it?

**Comment by randarnold** [comment]
You can change it, it just takes a long time for the other albums to appear. See my comment here [#272](https://github.com/tilltue/TLPhotoPicker/issues/272#issuecomment-625320573)
