### ISSUE TITLE
Video quality suggestion

### ISSUE THREAD

**Issue by nCr78** [tilltue/TLPhotoPicker#87]
Hello! First of all I want to say thank you because this is a great project!

Since there is a configuration list, could you maybe throw the video quality in there too? You can have it at your preferred default of course but it'd be nice if the user could change it too.

TLPhotosPickerViewController.swift -> around line 485
...
fileprivate func showCamera() {
...
picker.videoQuality = .typeHigh
...

**Comment by tilltue** [comment]
@nCr78 
Thank you for your attention.
add configuration option : ce1cacef0447e55e2e06b7f34abef63bab431ac8

**Comment by nCr78** [comment]
Thank you for the quick response!!
