### ISSUE TITLE
Hi,Geat pod. One question about selecting Livephoto. 

### ISSUE THREAD

**Issue by brandy2015** [tilltue/TLPhotoPicker#88]
How can I present only livephoto without video and normal picture?

Really Thank you.

**Comment by tilltue** [comment]
@brandy2015 
😊Hi.
You can use this.

``` swift3
       var configure = TLPhotosPickerConfigure()
        let options = PHFetchOptions()
        options.predicate = NSPredicate(format: "mediaSubtype == %ld", PHAssetMediaSubtype.photoLive.rawValue)
```

**Comment by brandy2015** [comment]
Thank you very much😄

**Comment by brandy2015** [comment]
var configure = TLPhotosPickerConfigure()
        let options = PHFetchOptions()
        options.predicate = NSPredicate(format: "mediaSubtype == %ld", PHAssetMediaSubtype.photoLive.rawValue)

configure.fetchOption = options    // I think we need this one😁

**Comment by brandy2015** [comment]
Absolutely successfully！

**Comment by brandy2015** [comment]
One more question, how can I get the livephoto I selected from the album?

The result is an asset . How can I convert that to PHLivePhoto type? I try lots of time.😭
