### ISSUE TITLE
How to get video path?

### ISSUE THREAD

**Issue by H-Ghadirian** [tilltue/TLPhotoPicker#91]
I want to show video, how could I get video file or its path?

**Comment by tilltue** [comment]
@H-Ghadirian 
Please check this.
https://github.com/tilltue/TLPhotoPicker/issues/42

**Comment by H-Ghadirian** [comment]
`PHCachingImageManager().requestAVAsset(forVideo: asset.phAsset!, options: nil, resultHandler: {
                    (asset: AVAsset?, audioMix: AVAudioMix?, info: [AnyHashable : Any]?) in
                    DispatchQueue.main.async {
                        
                        let asset = asset as? AVURLAsset
                        print(asset?.url)
//                        var data = NSData(contentsOfURL: (asset?.url)!)
                    }
                })`

**Comment by H-Ghadirian** [comment]
`
PHCachingImageManager().requestAVAsset(forVideo: asset.phAsset!, options: nil, resultHandler: {
                    (asset: AVAsset?, audioMix: AVAudioMix?, info: [AnyHashable : Any]?) in
                    DispatchQueue.main.async {
                        
                        let asset = asset as? AVURLAsset
                        print(asset?.url)
//                        var data = NSData(contentsOfURL: (asset?.url)!)
                    }
                })
`
