### ISSUE TITLE
Show proper alerts when camera , microphone and photos permission is denied. 

### ISSUE THREAD

**Issue by rizwan95** [tilltue/TLPhotoPicker#93]
Show proper alerts when camera , microphone and photos permission is denied.

**Comment by tilltue** [comment]
@rizwan95 
Showing permission alert when use camera button or photo library.
That would be an issue?

**Comment by rizwan95** [comment]
We should show proper alerts when camera button is tapped or while getting photos when the user has disabled the camera / album permission from settings.

**Comment by rizwan95** [comment]
You have added authorization for checking camera using AVCaptureDevice.authorizationStatus. Similarly, please provide Photos access check using PHPhotoLibrary.authorizationStatus() == .denied.

**Comment by tilltue** [comment]
Oh i see.

**Comment by rizwan95** [comment]
Yes. You can check the forked repository if you want. https://github.com/rizwan95/TLPhotoPicker

**Comment by tilltue** [comment]
Fixed 9a3c8cb27c12910542a5ede3a680dd7f636fc7d3

**Comment by rizwan95** [comment]
Great! :)
